'QLTA': 'iShares Aaa A Rated Corporate B',
'QIA.SG': 'Qiagen N.V. Aandelen op naam EO',
'QLIFE.ST': 'QLife Holding AB',
'QUASX': 'AB Cap Fund',
'QUAZX': 'AB Cap Fund',
'QUAIX': 'AB Cap Fund',
'QUAYX': 'AB Cap Fund',
'QABA': 'First Trust NASDAQ ABA Communit',
'QLIRO.ST': 'Qliro AB',
'QIIWI.ST': 'Qiiwi Games AB',
'QBT.F': 'QUICKBIT EU AB  O.N.',
'QUARX': 'AB Cap Fund',
'QUACX': 'AB Cap Fund',
'QUART.ST': 'Quartiers Properties AB',
'QBT.BE': 'QUICKBIT EU AB  O.N.',
'QAIR.ST': 'QleanAir Holding AB',
'QLINEA.ST': 'Q-Linea AB',
'QBT.MU': 'QUICKBIT EU AB  O.N.',
'QABA.MX': 'FIRST TR NSQ ABA F UNIT COM SHS',
'QUART-PREF.ST': 'Quartiers Properties AB Pref',
'QUART-TO4.ST': 'Quartiers Properties AB TO4',
'QUAKX': 'AB Cap Fund',
'QUART-TO3.ST': 'Quartiers Properties AB TO3',
'QREARX': 'TIAA Real Estate Account',
'QCSTIX': 'CREF Stock Account - R3',
'QCGRIX': 'CREF Growth Account - R3',
'QCSTPX': 'CREF Stock Account - R2',
'QCSTRX': 'CREF Stock Account - R1',
'QCGRRX': 'CREF Growth Account - R1',
'QCEQPX': 'CREF Equity Index Account - R2',
'QCEQIX': 'CREF Equity Index Account - R3',
'QCGLIX': 'CREF Global Equities Account -',
'QCGRPX': 'CREF Growth Account - R2',
'QCGLRX': 'CREF Global Equities Account -',
'QCGLPX': 'CREF Global Equities Account -',
'QTAP': 'Innovator Growth Accelerated Pl',
'QCSCPX': 'CREF Social Choice Account - R2',
'QCSCIX': 'CREF Social Choice Account - R3',
'QCILIX': 'CREF Inflation-Linked Bond Acco',
'QCEQRX': 'CREF Equity Index Account - R1',
'QCBMPX': 'CREF Bond Market Account - R2',
'QCBMIX': 'CREF Bond Market Account - R3',
'QCILRX': 'CREF Inflation-Linked Bond Acco',
'QCILPX': 'CREF Inflation-Linked Bond Acco',
'QCSCRX': 'CREF Social Choice Account - R1',
'QCMMPX': 'CREF Money Market Account - R2',
'QCBMRX': 'CREF Bond Market Account - R1',
'QZG.SI': '$ Accrelist Ltd',
'QCMMRX': 'CREF Money Market Account - R1',
'QAGR11.SA': 'FII QUASAR ACI',
'QCP': 'None',
'QELL': 'Qell Acquisition Corp.',
'QELLW': 'Qell Acquisition Corp.',
'QELLU': 'Qell Acquisition Corp.',
'QFTA': 'Quantum FinTech Acquisition Cor',
'QFTA-UN': 'Quantum FinTech Acquisition Cor',
'QFTA-WT': 'Quantum FinTech Acquisition Cor',
'QA1A.BE': 'QELL ACQ. UT(1A+1/3WT.)',
'QVGMEX18.MX': 'ACTINVER CASA DE BOLSA SA DE CV',
'QTL.SG': 'Lumibird S.A. Actions Port. EO',
'QSV.SG': 'Edenred S.A. Actions Port. EO 2',
'QD': 'Qudian Inc.',
'QPX': 'AdvisorShares Q Dynamic Growth',
'QPT': 'AdvisorShares Q Portfolio Blend',
'QD2.F': 'ADACEL TECHS LTD.',
'QMGYX': 'Invesco Advantage International',
'QGI.SG': 'Mitra Adiperkasa Tbk',
'QSTAX': 'Quantified STF Fund - Advisor C',
'QNTAX': 'Meeder Quantex Fund - Adviser C',
'QMGCX': 'Invesco Advantage International',
'Q00254.MI': 'LQ BARR EXP ADNVTS 60 260922',
'QMGIX': 'Invesco Advantage International',
'QUAGX': 'Quaker Impact Growth Fund Advis',
'QMGAX': 'Invesco Advantage International',
'QMGRX': 'Invesco Advantage International',
'QC8.F': 'AFC ENERGY PLC  LS -',
'QC8.SG': 'AFC Energy PLC Registered Share',
'QC8.MU': 'AFC ENERGY PLC  LS -',
'QC8.BE': 'AFC ENERGY PLC  LS -',
'QC8.DU': 'AFC ENERGY PLC  LS -',
'QS6A.SG': 'Q-Soft Verwaltungs AG Namens-Ak',
'QSC.SG': 'QSC AG Namens-Aktien o.N.',
'QIE.TO': 'AGFIQ INTERNATIONAL EQUITY ETF',
'QBTL.TO': 'AGFIQ US MKT NEUT ANTIBETA CAD',
'QLMAAX': 'Legg Mason/QS Aggressive Model',
'QDXB.TO': 'MACKENZIE DEV EX NA AGG BOND ID',
'QBY.DE': 'Q.BEYOND AG NA O.N.',
'QBY.F': 'Q.BEYOND AG NA O.N.',
'QEF.NE': 'AGFiQ GLOBAL ESG FACTORS ETF',
'QBY.MU': 'Q.BEYOND AG NA O.N.',
'QGB.NE': 'AGFiQ CORE GLOBAL MULTI-SECTOR',
'QOU.HM': 'RIPAG AG  INH. O.N.',
'QB7.SG': 'Quirin Privatbank AG Inhaber-Ak',
'QCD.TO': 'AGFIQ CANADIAN EQUITY ETF',
'QBY.BE': 'Q.BEYOND AG NA O.N.',
'QLMABX': 'Legg Mason/QS Aggressive Model',
'QBY.HA': 'Q.BEYOND AG NA O.N.',
'QBY.HM': 'Q.BEYOND AG NA O.N.',
'QUS.TO': 'AGFIQ US EQUITY ETF',
'QIF.NE': 'AGFiQ GLOBAL INFRASTRUCTURE ETF',
'QBY.DU': 'Q.BEYOND AG NA O.N.',
'QMA.TO': 'AGFIQ GLOBAL BALANCED ETF PORTF',
'QEM.TO': 'AGFIQ EMERGING MARKETS EQUITY E',
'QBB.TO': 'MACKENZIE CDN AGGREGATE BOND IN',
'QLMADX': 'Legg Mason/QS Moderately Aggres',
'QLMACX': 'Legg Mason/QS Moderately Aggres',
'QLMGTX': 'ClearBridge Variable Aggressive',
'QLMGOX': 'ClearBridge Variable Aggressive',
'QH': 'Quhuo Limited - American Deposi',
'QRFT': 'QRAFT AI-Enhanced U.S. Large Ca',
'QAI': 'IQ Hedge MultiIQ Hedge Multi-St',
'QABSY': 'QANTAS AIRWAYS',
'QUBSF': 'QANTAS AIRWAYS',
'QAN.SG': 'QANTAS AIRWAYS LTD. Registered',
'QAN.BE': 'QANTAS AIRWAYS',
'QAN.F': 'QANTAS AIRWAYS',
'QAN.DU': 'QANTAS AIRWAYS',
'Q00268.MI': 'LQ BARR EXP AIRBUS/BOEING 60 15',
'QAN.HM': 'QANTAS AIRWAYS',
'QK': 'Q&K International Group Limited',
'QJQ.SG': 'ISS AS Indehaver Aktier DK 1',
'QVAL': 'Alpha Architect U.S. Quantitati',
'QMOM': 'Alpha Architect U.S. Quantitati',
'QVGIX': 'Invesco Global Allocation Fund',
'QSPRX': 'AQR Style Premia Alternative Fu',
'QSPIX': 'AQR Style Premia Alternative Fu',
'QVOPX': 'Invesco Fundamental Alternative',
'QAACX': 'Federated Hermes MDT All Cap Co',
'QAITX': 'Q3 All-Weather Tactical Fund In',
'QAMC.QA': 'Qatar Aluminium Manufacturing Q',
'QRPIX': 'AQR Alternative Risk Premia Fun',
'QIACX': 'Federated Hermes MDT All Cap Co',
'QGRNX': 'Invesco Global Allocation Fund',
'QATR.QA': 'Al Rayan Qatar ETF',
'QKACX': 'Federated Hermes MDT All Cap Co',
'QAISX': 'Q3 All-Weather Sector Rotation',
'QRPRX': 'AQR Alternative Risk Premia Fun',
'QAMC@S.QA': 'Qatar Aluminium Manufacturing Q',
'QALTX': 'Quantified Alternative Investme',
'QCACX': 'Federated Hermes MDT All Cap Co',
'QFAL.MI': 'QF ALPHA IMM',
'QRPNX': 'AQR Alternative Risk Premia Fun',
'QAWSX': 'Q3 All-Weather Sector Rotation',
'QOPNX': 'Invesco Fundamental Alternative',
'QOPIX': 'Invesco Fundamental Alternative',
'QOPYX': 'Invesco Fundamental Alternative',
'QGRCX': 'Invesco Global Allocation Fund',
'QCB.NE': 'MACKENZIE CANADIAN ALL CORPORAT',
'QALAX': 'Quantified Alternative Investme',
'QAWTX': 'Q3 All-Weather Tactical Fund In',
'QGRIX': 'Invesco Global Allocation Fund',
'QLA.BE': 'ALASKA COMM SYS H. DL-',
'QLA.F': 'ALASKA COMM SYS H. DL-',
'QSPNX': 'AQR Style Premia Alternative Fu',
'QOPCX': 'Invesco Fundamental Alternative',
'QGRYX': 'Invesco Global Allocation Fund',
'Q00276.MI': 'LQ BARR EXP ALAMEB 60 250124',
'Q00535.MI': 'LQ BARR EXP ALSSUN 50 050325',
'QCON': 'American Century ETF Trust Amer',
'QINT': 'American Century Quality Divers',
'QGRO': 'American Century STOXX U.S. Qua',
'QPFF': 'American Century ETF Trust Amer',
'QFI.F': 'AMER. FINL GRP',
'QFI.BE': 'AMER. FINL GRP',
'Q0U6.Z': 'STX AMER.600 REITS PR USD',
'Q00A.Z': 'STX AMERICAS 600 PR EUR',
'Q0UZ.Z': 'STX AMERICAS 600 PR.USD',
'QMJ': 'Direxion S&P 500 High minus Low',
'QMN': 'IQ Hedge Market Neutral Tracker',
'QFARE.MI': 'QF AMUNDI RE EUROPA',
'QCEU.MI': 'AMUNDI MSCI EUROPE QUAL FACTOR',
'QCEU.PA': 'AMUNDI MSCI EURQUA',
'QFARI.MI': 'QF AMUNDI RE ITALIA',
'Q00L.Z': 'STX AM600 BAS.RES.PR EUR',
'Q01L.Z': 'STX AM600 MEDIA RE EUR',
'Q00N.Z': 'STX AM600 BAS.RES.RE EUR',
'Q01K.Z': 'STX AM600 MEDIA PR USD',
'Q09G.Z': 'STX AM600 TR.+LEIS.RE USD',
'Q016.Z': 'STX AM600 TECHN.PR EUR',
'Q00T.Z': 'STX AM600 CON.+MAT.PR EUR',
'Q01X.Z': 'STX AM600 RE.EST.PR EUR',
'Q01C.Z': 'STX AM600 I.G.+SER.RE EUR',
'Q008.Z': 'STX AM600 HEALTH C.PR USD',
'Q014.Z': 'STX AM600 RETAIL RE EUR',
'Q001.Z': 'STX AM600 FIN.SERV.RE USD',
'Q00J.Z': 'STX AM600 BANKS RE EUR',
'Q09H.Z': 'STX AM600 UTIL. PR EUR',
'Q00V.Z': 'STX AM600 CON+MAT PR USD',
'Q00Q.Z': 'STX AM600 CHEM. PR EUR',
'Q01I.Z': 'STX AM600 INSUR. RE USD',
'Q00Z.Z': 'STX AM600 FIN.SERV.PR USD',
'Q015.Z': 'STX AM600 RETAIL RE USD',
'Q01Y.Z': 'STX AM600 RE.EST.PR USD',
'Q00S.Z': 'STX AM600 CHEM. RE EUR',
'Q00U.Z': 'STX AM600 CHEM RE USD',
'Q09F.Z': 'STX AM600 TR.+LEIS.RE EUR',
'Q09D.Z': 'STX AM600 TR.+LEIS.PR EUR',
'Q01J.Z': 'STX AM600 MEDIA PR EUR',
'Q013.Z': 'STX AM600 RETAIL PR USD',
'Q09I.Z': 'STX AM600 UTIL. PR USD',
'Q09A.Z': 'STX AM600 TELECOMM.PR USD',
'Q09E.Z': 'STX AM600 TR.+LEIS.PR USD',
'Q09C.Z': 'STX AM600 TELECOMM.RE USD',
'Q017.Z': 'STX AM600 TECHN. PR USD',
'Q01D.Z': 'STX AM600 I.G.+SER.RE USD',
'Q00W.Z': 'STX AM600 CON+MAT RE EUR',
'Q010.Z': 'STX AM600 TELECOMM.PR EUR',
'Q00P.Z': 'STX AM600 BAS.RES.RE USD',
'Q01A.Z': 'STX AM600 I.G.+SER.PR EUR',
'Q01Z.Z': 'STX AM600 RE.EST.RE EUR',
'Q01F.Z': 'STX AM600 INSUR. PR USD',
'Q019.Z': 'STX AM600 TECHN. RE USD',
'Q01M.Z': 'STX AM600 MEDIA RE USD',
'Q007.Z': 'STX AM600 HEALTH C.PR EUR',
'Q00G.Z': 'STX AM600 AUT.+PTS.RE USD',
'Q009.Z': 'STX AM600 HEALTH C.RE EUR',
'Q00E.Z': 'STX AM600 AUT.+PTS.PR USD',
'Q002.Z': 'STX AM600 FIN.SERV.RE EUR',
'Q012.Z': 'STX AM600 RETAIL PR EUR',
'Q00R.Z': 'STX AM600 CHEM. PR USD',
'Q01B.Z': 'STX AM600 I.G.+SER.PR USD',
'Q00K.Z': 'STX AM600 BANKS RE USD',
'Q000.Z': 'STX AM600 HEALTH C.RE USD',
'Q011.Z': 'STX AM600 RE.EST.RE USD',
'Q00Y.Z': 'STX AM600 FIN.SERV.PR EUR',
'Q01E.Z': 'STX AM600 INSUR. PR EUR',
'Q00I.Z': 'STX AM600 BANKS PR USD',
'Q09B.Z': 'STX AM600 TELECOMM.RE EUR',
'Q00M.Z': 'STX AM600 BAS.RES PR USD',
'Q00D.Z': 'STX AM600 AUT.+PTS.PR EUR',
'Q00H.Z': 'STX AM600 BANKS PR EUR',
'Q018.Z': 'STX AM600 TECHN. RE EUR',
'Q00X.Z': 'STX AM600 CON+MAT RE USD',
'Q00F.Z': 'STX AM600 AUT.+PTS.RE EUR',
'Q09K.Z': 'STX AM600 UTIL. RE USD',
'Q01G.Z': 'STX AM600 INSUR. RE EUR',
'Q09J.Z': 'STX AM600 UTIL. RE EUR',
'QCCU.V': 'QC COPPER AND GOLD INC',
'QCCUF': 'QC COPPER AND GOLD INC',
'QEX.V': 'QUESTEX GOLD AND COPPER LTD',
'QHHR.BK': 'QUALITY HOUSES HOTEL AND RESIDE',
'QGRI.QA': 'Qatar General Insurance and Rei',
'QCFS.QA': 'Qatar Cinema and Film Distribut',
'QEWS.QA': 'Qatar Electricity and Water QPS',
'QEWS@S.QA': 'Qatar Electricity and Water QPS',
'Q00216.MI': 'LQ EXP ANGLO/BGOLD/FCX/WPM 60 1',
'QDVQ.SG': 'iShares Fallen Angels High Yiel',
'QLMI.QA': 'QLM Life and Medical Insurance',
'Q0AR.Z': 'STX A/P600 MEDIA PR EUR',
'QR9.SI': 'PRINCIPAL S&P AP DIV S$D',
'Q00555.MI': 'LQ BARR EXP APFBTA 150 050422',
'Q0BH.Z': 'STX A/P600 TELECOM.PR USD',
'Q0BJ.Z': 'STX A/P600 TELECOM.RE EUR',
'QGJ22.NYM': 'E-mini Natural Gas Futures',
'QMJ22.NYM': 'E-mini Crude Oil Futures',
'QLMAOX': 'ClearBridge Variable Appreciati',
'Q09Z.Z': 'STX A/P600 CHEM.PR USD',
'Q0BR.Z': 'STX A/P600 UTIL. RE EUR',
'QO95.Z': 'STX A/P600 CON+MAT RE EUR',
'Q0AE.Z': 'STX A/P600 HEAL.CA.PR EUR',
'Q096.Z': 'STX A/P600 CON+MAT RE USD',
'Q0AH.Z': 'STX A/P600 HEAL.CA.RE USD',
'Q09T.Z': 'STX A/P600 BANKS RE USD',
'Q0AL.Z': 'STX A/P600 I.G.+SE.RE USD',
'Q09V.Z': 'STX A/P600 BAS.RES.PR USD',
'Q0BB.Z': 'STX A/P600 RETAIL RE USD',
'Q09Y.Z': 'STX A/P600 CHEM. PR EUR',
'Q0A0.Z': 'STX A/P600 RETAIL PR USD',
'Q0AS.Z': 'STX A/P600 MEDIA PR USD',
'Q09M.Z': 'STX A/P600 AU.+PTS.PR.USD',
'Q0AM.Z': 'STX A/P600 INSUR.PR EUR',
'Q0U3.Z': 'STX GL1800 EX A/P PR.USD',
'Q0BQ.Z': 'STX A/P600 UTIL. PR USD',
'Q09U.Z': 'STX A/P600 BAS.RES.PR EUR',
'Q09S.Z': 'STX A/P600 BANKS RE EUR',
'Q0BK.Z': 'STX A/P600 TR.+LEI.PR EUR',
'Q0BN.Z': 'STX A/P600 TR.+LEI.RE USD',
'Q0AQ.Z': 'STX A/P600 INSUR.RE USD',
'Q091.Z': 'STX A/P600 CHEM.RE EUR',
'Q097.Z': 'STX A/P600 FIN.SER.PR EUR',
'Q09W.Z': 'STX A/P600 BAS.RES.RE EUR',
'Q098.Z': 'STX A/P600 FIN.SER.PR USD',
'Q0BL.Z': 'STX A/P600 TR.+LEI.PR USD',
'Q0AT.Z': 'STX A/P600 MEDIA RE EUR',
'Q09X.Z': 'STX A/P600 BAS.RES.RE USD',
'Q09R.Z': 'STX A/P600 BANKS PR USD',
'Q094.Z': 'STX A/P600 CON+MAT PR USD',
'Q0BI.Z': 'STX A/P600 TELECOM.RE USD',
'Q09N.Z': 'STX A/P600 AU.+PTS.RE EUR',
'Q0BP.Z': 'STX A/P600 UTIL. PR EUR',
'Q09L.Z': 'STX A/P600 AU.+PTS.PR EUR',
'Q099.Z': 'STX A/P600 FIN.SER.RE EUR',
'Q0A8.Z': 'STX A/P600 RE.EST RE USD',
'Q0A7.Z': 'STX A/P600 RE.EST RE EUR',
'Q0AU.Z': 'STX A/P600 MEDIA RE USD',
'Q0AN.Z': 'STX A/P600 INSUR.PR USD',
'Q0BF.Z': 'STX A/P600 TECHN. RE USD',
'Q090.Z': 'STX A/P600 FIN.SER.RE USD',
'Q093.Z': 'STX A/P600 CON+MAT PR EUR',
'Q0A9.Z': 'STX A/P600 RETAIL PR EUR',
'Q09Q.Z': 'STX A/P600 BANKS PR EUR',
'Q0AP.Z': 'STX A/P600 INSUR.RE EUR',
'Q0BM.Z': 'STX A/P600 TR.+LEI.RE EUR',
'Q0BG.Z': 'STX A/P600 TELECOM.PR EUR',
'Q0A6.Z': 'STX A/P600 RE.EST PR USD',
'Q092.Z': 'STX A/P600 CHEM.RE USD',
'Q0AG.Z': 'STX A/P600 HEAL.CA.RE EUR',
'Q0AK.Z': 'STX A/P600 I.G.+SE.RE EUR',
'Q0BD.Z': 'STX A/P600 TECHN. PR USD',
'Q0BS.Z': 'STX A/P600 UTIL. RE USD',
'Q0A5.Z': 'STX A/P600 RE.EST.PR EUR',
'Q0BE.Z': 'STX A/P600 TECHN. RE EUR',
'Q0BC.Z': 'STX A/P600 TECHN. PR EUR',
'Q0BA.Z': 'STX A/P600 RETAIL RE EUR',
'Q0AJ.Z': 'STX A/P600 I.G.+SE.PR USD',
'Q0AI.Z': 'STX A/P600 I.D.+SE.PR EUR',
'Q0AF.Z': 'STX A/P600 HEAL.CA.PR USD',
'Q09P.Z': 'STX A/P600 AU.+PTS.RE USD',
'QMNIX': 'AQR Equity Market Neutral Fund',
'QLEIX': 'AQR Long-Short Equity Fund Clas',
'Q': 'None',
'QMNNX': 'AQR Equity Market Neutral Fund',
'QLENX': 'AQR Long-Short Equity Fund Clas',
'QMHIX': 'AQR Managed Futures Strategy HV',
'QUERX': 'AQR Large Cap Defensive Style F',
'QCPIX': 'AQR Core Plus Bond Fund - Class',
'QRCRX': 'AQR Risk-Balanced Commodities S',
'QCERX': 'AQR Large Cap Multi-Style Fund',
'QTERX': 'AQR TM Emerging Multi-Style - C',
'QEELX': 'AQR Emerging Multi-Style Fund -',
'QCELX': 'AQR Large Cap Multi-Style Fund',
'QTLLX': 'AQR TM Large Cap Multi-Style -',
'QICRX': 'AQR International Multi-Style F',
'QEENX': 'AQR Emerging Multi-Style Fund -',
'QSMRX': 'AQR Small Cap Momentum Style Fu',
'QIORX': 'AQR International Momentum Styl',
'QTMRX': 'AQR TM Large Cap Momentum Style',
'QMORX': 'AQR Large Cap Momentum Style Fu',
'QSSNX': 'AQR TM Small Cap Multi-Style -',
'QDSNX': 'AQR Diversifying Strategies Fun',
'QTSRX': 'AQR TM Small Cap Momentum Style',
'QSSLX': 'AQR TM Small Cap Multi-Style -',
'QCPRX': 'AQR Core Plus Bond Fund - Class',
'QGMNX': 'AQR Global Macro Fund Class N',
'QRMIX': 'AQR Risk Parity II MV Fund Clas',
'QSERX': 'AQR Small Cap Multi-Style Fund',
'QIMLX': 'AQR TM International Multi-Styl',
'QDARX': 'AQR Diversified Arbitrage Fund',
'QICLX': 'AQR International Multi-Style F',
'QIMRX': 'AQR TM International Multi-Styl',
'QGMRX': 'AQR Global Macro Fund - Class R',
'QMHNX': 'AQR Managed Futures Strategy HV',
'QTIRX': 'AQR TM International Momentum S',
'QRMRX': 'AQR Risk Parity II MV Fund - Cl',
'QSSRX': 'AQR TM Small Cap Multi-Style -',
'QICNX': 'AQR International Multi-Style F',
'QIMNX': 'AQR TM International Multi-Styl',
'QCENX': 'AQR Large Cap Multi-Style Fund',
'QMNRX': 'AQR Equity Market Neutral Fund',
'QLERX': 'AQR Long-Short Equity Fund - Cl',
'QCPNX': 'AQR Core Plus Bond Fund - Class',
'QMHRX': 'AQR Managed Futures Strategy HV',
'QSMNX': 'AQR Small Cap Multi-Style Fund',
'QDSIX': 'AQR Diversifying Strategies Fun',
'QGMIX': 'AQR Global Macro Fund Class I',
'QTLNX': 'AQR TM Large Cap Multi-Style -',
'QTENX': 'AQR TM Emerging Multi-Style - C',
'QECRX': 'AQR Emerging Multi-Style Fund -',
'QTELX': 'AQR TM Emerging Multi-Style - C',
'QSMLX': 'AQR Small Cap Multi-Style Fund',
'QTLRX': 'AQR TM Large Cap Multi-Style -',
'QRMNX': 'AQR Risk Parity II MV Fund Clas',
'QDSRX': 'AQR Diversifying Strategies Fun',
'QFUEL.OL': 'QUANTAFUEL ASA',
'QFR.OL': 'Q-FREE ASA',
'QNTFF': 'QUANTAFUEL ASA',
'QS0.SI': 'PRINCIPAL ASEAN40 S$D',
'Q9W1.F': 'ASHANTI SANKOFA',
'Q9W1.BE': 'ASHANTI SANKOFA',
'QL3.SI': 'IS ASIA HYG S$D',
'QL2.SI': 'IS ASIA BND S$D',
'Q00B.Z': 'STX ASIA/PAC. 600 PR EUR',
'Q0U1.Z': 'STX ASIA/PAC.600 PR.USD',
'QSR': 'Restaurant Brands International',
'QQQ3.L': 'WISDOMTREE MULTI ASSET ISSUER P',
'QQQS.L': 'WISDOMTREE MULTI ASSET ISSUER P',
'QLMHIX': 'Western Asset Core Plus VIT Por',
'QRRY': 'QUARRY CITY SVGS & LN ASSN',
'QLMYTX': 'Western Asset Variable Global H',
'QLMYIX': 'Western Asset Variable Global H',
'QSY': 'WisdomTree U.S. Quality Shareho',
'QAT': 'iShares MSCI Qatar ETF',
'QGRPX': 'UBS US Quality Growth At Reason',
'QFATL.MI': 'QF ATLANTIC 1',
'QO=F': 'E-mini Gold Futures',
'QCQ21.CMX': 'E-mini Copper Futures',
'QNT-AUD': 'Quant AUD',
'QA9.F': 'AUSTRAL.PRIMARY HEMP LTD',
'QMQ21.NYM': 'E-mini Crude Oil Futures',
'QFOA.F': 'AUSTAR GOLD LTD',
'QRL.F': 'AURIZON HLDGS LTD',
'QOQ21.CMX': 'E-mini Gold Futures',
'QASH-AUD': 'QASH AUD',
'QRK-AUD': 'Quark AUD',
'QRL-AUD': 'QuantumResistantLedger AUD',
'QTUM-AUD': 'Qtum AUD',
'QRL.MU': 'AURIZON HLDGS LTD',
'QRL.SG': 'Aurizon Holdings Ltd. Registere',
'QGQ21.NYM': 'E-mini Natural Gas Futures',
'QOQ22.CMX': 'E-mini Gold Futures',
'Q0BT.Z': 'STX GL1800 AU.+PTS.PR USD',
'QEMAX': 'Pear Tree Axiom Emerging Market',
'QFFOX': 'Pear Tree Axiom Emerging Market',
'QFFRX': 'Pear Tree Axiom Emerging Market',
'QOL.SG': 'SOL S.P.A. Azioni nom. EO 0',
'QCG.SG': 'CALTAGIRONE S.P.A. Azioni nom.',
'Q00100.MI': 'LQ BARR EXP AZN/BAYN/GSK/SAN 60',
'Q00164.MI': 'LQ BARR EXP A2IMPI 65 241025',
'Q00186.MI': 'LQ BARR EXP A2A/STL/UNICREDIT 6',
'Q00492.MI': 'LQ BARR EXP A2A/ENI/TELECOM 60',
'Q00238.MI': 'LQ BARR EXP BABA/INTEL/TWITTER',
'QDVP.SG': 'iShares US Mortgage Backed Secu',
'QYBX': 'QIAN YUAN BAIXING INC',
'QBAK': 'QUALSTAR CORP',
'QCIBX': 'QCI Balanced Fund Institutional',
'QKBGX': 'Federated Hermes MDT Balanced F',
'QCBGX': 'Federated Hermes MDT Balanced F',
'QABGX': 'Federated Hermes MDT Balanced F',
'QIBGX': 'Federated Hermes MDT Balanced F',
'QBAN': 'TELCO CUBA INC',
'QNBK.QA': 'Qatar National Bank QPSC',
'QNTO': 'QUAINT OAK BANCORP INC',
'QIBK.QA': 'Qatar Islamic Bank QPSC',
'QFBQ@S.QA': 'Qatar First Bank LLC',
'QIBK@S.QA': 'Qatar Islamic Bank QPSC',
'QFBQ.QA': 'Qatar First Bank LLC',
'QIIK@S.QA': 'Qatar International Islamic Ban',
'QNBK@S.QA': 'Qatar National Bank QPSC',
'Q0BU.Z': 'STX GL1800 BANKS PR USD',
'Q00493.MI': 'LQ BARR EXP BP/CHEVR/REPSOL 60',
'Q00275.MI': 'LQ BARR EXP GENERALI/ENEL/ENI 6',
'Q00252.MI': 'LQ BARR EXP NETFLIX/SPOTIFY 60',
'Q00247.MI': 'LQ BARR EXP TESLA/VARTA 60 2303',
'Q00187.MI': 'LQ BARR EXP ENIISP 60 011223',
'Q00534.MI': 'LQ BARR EXP ENIISP 50 290825',
'Q00515.MI': 'LQ BARR EXP FERRARI/ENEL 50 230',
'Q00277.MI': 'LQ BARR EXP HMINZA 60 190124',
'Q00278.MI': 'LQ BARR EXP EDF/ENEL/NEXTERA 65',
'Q00296.MI': 'LQ BARR EXP EDF/RWE/UNICREDIT 5',
'Q00240.MI': 'LQ BARR EXP ENLEUN 60 160326',
'Q00530.MI': 'LQ BARR EXP BPER/ENI/PIRELLI 60',
'Q00192.MI': 'LQ BARR EXP BAYN/ING/NOKIA/TEF',
'Q00257.MI': 'LQ BARR EXP MPMLTM 50 260324',
'Q00514.MI': 'LQ BARR EXP DARPST 60 250825',
'Q00265.MI': 'LQ BARR EXP NORDEX/VARTA 50 010',
'Q00166.MI': 'LQ BARR EXP CISCO/GE/PINTEREST',
'Q00545.MI': 'LQ OUTPERF BCHFFC 100 250924',
'QDVY.MU': 'ISHSII-DL FR BD ETF DLUD',
'QDVZ.MU': 'ISHSII-DL FR BD ETF LSHD',
'QDVY.DE': 'ISHSII-DL FR BD ETF DLUD',
'QDVY.DU': 'ISHSII-DL FR BD ETF DLUD',
'QDVY.F': 'ISHSII-DL FR BD ETF DLUD',
'QDV4.MU': 'ISHSII-DL FR BD ETF DLACC',
'QDVY.BE': 'ISHSII-DL FR BD ETF DLUD',
'QLTY.AX': 'BETA QLTY ETF UNITS',
'QRE.AX': 'BETAASXRES ETF UNITS',
'QFN.AX': 'BETAASXFIN ETF UNITS',
'QAU.AX': 'BETA GOLD ETF UNITS',
'QPON.AX': 'BETAQPON ETF UNITS',
'QUS.AX': 'BETA QUS ETF UNITS',
'QOZ.AX': 'BETARAFI ETF UNITS',
'QCTA.MU': 'BELDEN INC.  DL -',
'QCTA.F': 'BELDEN INC.  DL -',
'Q0UL.Z': 'STX GL1800 FD+BEV. PR USD',
'QBIO': 'Q BIOMED INC',
'QBTC-U.TO': 'THE BITCOIN FUND',
'QSAM': 'QSAM BIOSCIENCES INC',
'QTXB': 'QUANTRIX BIOMEDICAL CORPORATION',
'Q95.Z': 'STXE TM BIOTECH RE USD',
'Q5H.Z': 'STXE TM PHAR.+BIOT.PR EUR',
'Q5K.Z': 'STXE TM PHAR.+BIOT.RE EUR',
'Q5L.Z': 'STXE TM PHAR.+BIOT.RE USD',
'Q92.Z': 'STXE TM BIOTECH PR EUR',
'Q93.Z': 'STXE TM BIOTECH PR USD',
'Q94.Z': 'STXE TM BIOTECH RE EUR',
'Q5J.Z': 'STXE TM PHAR.+BIOT.PR USD',
'QBT.L': 'QUANTUM BLOCKCHAIN TECHNOLOGIES',
'QHY.TO': 'MACKENZIE US HIGH YLD BND IDX C',
'QUEU.DE': 'BNPPE.-E.QU.EU.UECEO',
'QUED.F': 'BNPPE.-E.QA.EU.UEDEO',
'QUED.PA': 'BNPP EASYQUALITYD',
'QUED.SG': 'BNP PARIBAS EASY-EQ.QUAL.EUR.-U',
'QUED.DU': 'BNPPE.-E.QA.EU.UEDEO',
'QUEJ.BE': 'BNPPE-M.JAP.SRI SS5 UETFC',
'QUED.DE': 'BNPPE.-E.QA.EU.UEDEO',
'QUEU.F': 'BNPPE.-E.QU.EU.UECEO',
'QUEU.DU': 'BNPPE.-E.QU.EU.UECEO',
'QUEU.SG': 'BNP Paribas Easy Equity Quality',
'QUEU.MU': 'BNPPE.-E.QU.EU.UECEO',
'QSB.TO': 'MACKENZIE CDN SHORT TERM BOND I',
'QEBH.TO': 'MACKENZIE EMERGING MKTS BOND IN',
'QWVQX': 'Clearwater Tax Exempt Bond Fd',
'QDVY.SG': 'iShares $ Floating Rate Bond UC',
'QNC1.BE': 'BONTERRA ENERGY CORP.',
'QNC1.SG': 'Bonterra Energy Corp. Registere',
'QNC1.F': 'BONTERRA ENERGY CORP.',
'QSR.TO': 'RESTAURANT BRANDS INTERNATIONAL',
'QSRN.MX': 'RESTAURANT BRANDS INTL INC',
'QSP-UN.TO': 'RESTAURANT BRANDS INTL LTD PART',
'QD7Z.DE': 'I.XTRA.MSCI BRAZ.1C SEK',
'QS': 'QuantumScape Corporation',
'QTUM-BTC': 'Qtum BTC',
'QNT-BTC': 'Quant BTC',
'QRK-BTC': 'Quark BTC',
'QASH-BTC': 'QASH BTC',
'QRL-BTC': 'QuantumResistantLedger BTC',
'QGLDX': 'The Gold Bullion Strategy Fund',
'QMAR': 'FT Cboe Vest Growth-100 Buffer',
'QDEC': 'FT Cboe Vest Growth-100 Buffer',
'QUANTBUILD.BO': 'QUANTUM BUILD-TECH LTD',
'QGLCX': 'The Gold Bullion Strategy Fund',
'QASH-CAD': 'QASH CAD',
'QNT-CAD': 'Quant CAD',
'QTUM-CAD': 'Qtum CAD',
'QRK-CAD': 'Quark CAD',
'QRL-CAD': 'QuantumResistantLedger CAD',
'QYLD': 'Global X NASDAQ-100 Covered Cal',
'QYLG': 'Global X Nasdaq 100 Covered Cal',
'QCG.F': 'CALTAGIRONE SPA  EO 1',
'QCAN': 'None',
'QCN.TO': 'MACKENZIE CANADIAN EQUITY INDEX',
'QRC.V': 'QUEENS ROAD CAPITAL INVESTMENT',
'QCAAF': 'QUINSAM CAPITAL CORP',
'QTCI': 'QUANTUM CAPITAL INC',
'QTZ.AQ': 'QUETZAL CAPITAL',
'Q9L.BE': 'ST PETER PORT CAPITAL',
'QDVG.SG': 'iShares S&P 500 Health Care Sec',
'QDVL.DU': 'ISHSII-EO CB 0-3Y ESG EOD',
'QDVL.BE': 'ISHSII-EO CB 0-3Y ESG EOD',
'QDVL.DE': 'ISHSII-EO CB 0-3Y ESG EOD',
'QDVL.F': 'ISHSII-EO CB 0-3Y ESG EOD',
'QAMI11.SA': 'FII QUASAR CCI',
'QCE.TO': 'MACKENZIE CDN LARGE CAP EQUITY',
'QNCD.QA': 'Qatar National Cement QPSC',
'QEN.DU': 'CENTENE CORP.  DL-',
'QDFD.DE': 'FLSHI DM HD CEE DLD',
'QDFD.F': 'FLSHI DM HD CEE DLD',
'QEN.SG': 'CENTENE CORP. Registered Shares',
'QVFD.DE': 'FLSHI DM LV CEE DLA',
'QVFD.DU': 'FLSHI DM LV CEE DLA',
'QDFD.MU': 'FLSHI DM HD CEE DLD',
'QEN.F': 'CENTENE CORP.  DL-',
'QEN.MU': 'CENTENE CORP.  DL-',
'QVFD.MU': 'FLSHI DM LV CEE DLA',
'QDFD.DU': 'FLSHI DM HD CEE DLD',
'QVFD.BE': 'FLSHI DM LV CEE DLA',
'QVFD.F': 'FLSHI DM LV CEE DLA',
'Q9S.F': 'CHAMPION REAL EST. UTS',
'Q9S.BE': 'CHAMPION REAL EST. UTS',
'QHC': 'None',
'QUC.F': 'QUAKER CHEMICAL CORP. DL1',
'QUC.MU': 'QUAKER CHEMICAL CORP. DL1',
'Q0BW.Z': 'STX GL1800 CHEM.PR USD',
'QES.SI': 'ChinaSunsine',
'QCH.NE': 'MACKENZIE CHINA A-SHARES CSI 30',
'QCA1.BE': 'CHINAAMC CSI 300 IDX ETF',
'QCA2.MU': 'CHINAAMC HG SG SMALLC.IDX',
'Q0X.SI': '$ Ley Choon',
'QUCT': 'QUEEN CITY INVESTMENTS INC',
'QXM.TO': 'CI MORNINGSTAR NB QUEBEC ETF',
'QIT1.SG': 'CIT Group Inc. New Registered S',
'QIT1.F': 'CIT GROUP INC. NEW DL-',
'QIFF11.SA': 'FII QUATA   CI',
'QIT1.BE': 'CIT GROUP INC. NEW DL-',
'QBR-B.TO': 'QUEBECOR INC CLASS B SV',
'QBR-A.TO': 'QUEBECOR INC CLASS A MV',
'QADB.SG': 'QAD Inc. Registered Shares Clas',
'QDVCX': 'Quality Dividend Fund- Class C',
'QDVAX': 'Quality Dividend Fund- Class A',
'QLC': 'FlexShares Trust FlexShares US',
'QLD': 'ProShares Ultra QQQ',
'QCLN': 'First Trust NASDAQ Clean Edge G',
'QLMVIX': 'ClearBridge Variable Large Cap',
'QLMPTX': 'ClearBridge Variable Mid Cap Po',
'QCVAX': 'Clearwater International Fd',
'QWVOX': 'Clearwater Small Companies Fund',
'QLMEIX': 'ClearBridge Variable Dividend S',
'QLMLOX': 'ClearBridge Variable Large Cap',
'QLMMIX': 'ClearBridge Variable Mid Cap Po',
'QWVPX': 'Clearwater Core Equity Fund',
'QLMETX': 'ClearBridge Variable Dividend S',
'QLMSIX': 'ClearBridge Variable Small Cap',
'QLMSTX': 'ClearBridge Variable Small Cap',
'QLI': 'Qilian International Holding Gr',
'QCLN.TO': 'FIRST TRUST NSDQ CLN EDG GREEN',
'QCLN.AS': 'FT CLN EDG GRN NRG',
'QLS': 'IQ Hedge Long Short Tracker ETF',
'QLT': 'None',
'QLV': 'FlexShares US Quality Low Volat',
'QRL-CNY': 'QuantumResistantLedger CNY',
'QRK-CNY': 'Quark CNY',
'QASH-CNY': 'QASH CNY',
'QTUM-CNY': 'Qtum CNY',
'QNT-CNY': 'Quant CNY',
'QCOM': 'QUALCOMM Incorporated',
'QUBT': 'QUANTUM COMPUTING INC',
'QH.BK': 'QUALITY HOUSES PUBLIC COMPANY L',
'QNXC': 'QENEX COMMUNICATIONS INC',
'QRT.L': 'QUARTO GROUP INCORPORATED COM S',
'QCGDX': 'Quantified Common Ground Fund I',
'QTC.BK': 'QTC ENERGY PUBLIC COMPANY LIMIT',
'QUID.L': 'PIMCO ETFS PUBLIC LIMITED COMPA',
'QC1.F': 'NY COM.BANC.  DL-',
'QCH.F': 'COMPUTERSHARE LTD.',
'QLT.BK': 'QUALITECH PUBLIC COMPANY LIMITE',
'QH-R.BK': 'QUALITY HOUSES PUBLIC COMPANY L',
'QTC-R.BK': 'QTC ENERGY PUBLIC COMPANY LIMIT',
'QCH.BE': 'COMPUTERSHARE LTD.',
'QC1.BE': 'NY COM.BANC.  DL-',
'Q7Z.Z': 'STXE TM COMP.SERV. PR USD',
'QLT-R.BK': 'QUALITECH PUBLIC COMPANY LIMITE',
'Q70.Z': 'STXE TM COMP.SERV. PR EUR',
'Q71.Z': 'STXE TM COMP.SERV. RE EUR',
'Q72.Z': 'STXE TM COMP.SERV. RE USD',
'QEDN': 'QED CONNECT INC',
'Q-CON.BK': 'QUALITY CONSTRUCTION PRODUCTS',
'QLMAJX': 'Legg Mason/QS Conservative Mode',
'QLMLFX': 'QS Variable Conservative Growth',
'Q-CON-R.BK': 'QUALITY CONSTRUCTION PRODUCTS',
'QLMAIX': 'Legg Mason/QS Conservative Mode',
'QLMAHX': 'Legg Mason/QS Moderately Conser',
'QVCIIX': 'QS Variable Conservative Growth',
'QLMAGX': 'Legg Mason/QS Moderately Conser',
'QDVK.SG': 'iShares S&P 500 Consumer Discre',
'Q.MX': 'QUALITAS CONTROLADORA SAB DE CV',
'QQC': 'Simplify Nasdaq 100 PLUS Convex',
'QC=F': 'E-mini Copper Futures',
'QCN21.CMX': 'E-mini Copper Futures',
'QCU21.CMX': 'E-mini Copper Futures',
'QCZ21.CMX': 'E-mini Copper Futures',
'QCQ.F': 'CORDY OILFIELD SERVICES',
'QDVU.BE': 'ISHSVII-CORE S+P500 LSHDI',
'QDVJ.MU': 'ISHSIII-CORE GL.A.BD DLAH',
'QDEL': 'Quidel Corporation',
'QRTEA': 'Liberty Interactive Corporation',
'QMCO': 'Quantum Corporation',
'QUIK': 'QuickLogic Corporation',
'QTRX': 'Quanterix Corporation',
'QTMM': 'QUANTUM MATERIALS CORP',
'QRHC': 'Quest Resource Holding Corporat',
'QIPT': 'Quipt Home Medical Corp.',
'QIPT.V': 'QUIPT HOME MEDICAL CORP',
'QMCQF': 'QMC QUANTUM MINERALS CORPORATIO',
'QUMU': 'Qumu Corporation',
'QUESS.NS': 'QUESS CORP LTD',
'QRTEB': 'Liberty Interactive Corporation',
'QNBC': 'QNB CORP',
'QOIL': 'QUEST OIL CORPORATION',
'QMC.V': 'QMC QUANTUM MINERALS CORP',
'QS-WT': 'QuantumScape Corporation',
'QEC.TO': 'QUESTERRE ENERGY CORP',
'QNC.V': 'QUANTUM NUMBERS CORP',
'QSPW': 'QUANTUM SOLAR POWER CORP',
'QPRC': 'QUEST PATENT RESEARCH CORPORATI',
'QPM.V': 'QUEBEC PRECIOUS METALS CORPORAT',
'QNCCF': 'QUANTUM NUMBERS CORP',
'QMIS': 'QMIS FINANCE SECURITIES CORP',
'QCX.V': 'QCX GOLD CORP',
'QUAN': 'QUANTUM INTERNATIONAL CORP(US)',
'QQQFF': 'QUIZAM MEDIA CORP',
'QTEYF': 'QUESTERRE ENERGY CORP',
'QDEL.MX': 'QUIDEL CORP',
'QSGC.F': 'SKY GOLD CORP. NEW',
'QM01.F': 'DESERT MOUNTAIN EGY CORP.',
'QUESS.BO': 'Quess Corp Limited',
'QST1.SG': 'Qualstar Corp. Registered Share',
'QLDN.SG': 'Elysee Development Corp. Regist',
'QCXGF': 'QCX GOLD CORP',
'QSU.SG': 'SCSK Corp. Registered Shares o.',
'QS.MX': 'QUANTUMSCAPE CORPORATION',
'QKL1.F': 'QUICKLOGIC CORP.  DL-',
'QMC.F': 'SMC CORP.',
'QPJ.SG': 'Kewpie Corp. Registered Shares',
'QNT2.DE': 'QUANTUM CORP. DSSG DL-',
'QNT2.DU': 'QUANTUM CORP. DSSG DL-',
'QSGC.BE': 'SKY GOLD CORP. NEW',
'QE1.F': 'QUESTERRE ENERGY CORP. A',
'QL1.SG': 'QUIDEL CORP. Registered Shares',
'QM01.BE': 'DESERT MOUNTAIN EGY CORP.',
'QNT2.F': 'QUANTUM CORP. DSSG DL-',
'QE1.SG': 'Questerre Energy Corp. Register',
'QSU.MU': 'SCSK CORP.',
'QM01.MU': 'DESERT MOUNTAIN EGY CORP.',
'QNT2.MU': 'QUANTUM CORP. DSSG DL-',
'QYLD.MX': 'GLOBAL X FDS NASDAQ 100 COVERED',
'QM=F': 'E-mini Crude Oil Futures',
'QMN21.NYM': 'E-mini Crude Oil Futures',
'QCMMIX': 'CREF Money Market Account - R3',
'QMU21.NYM': 'E-mini Crude Oil Futures',
'QMX21.NYM': 'E-mini Crude Oil Futures',
'QMZ23.NYM': 'E-mini Crude Oil Futures',
'QMM23.NYM': 'E-mini Crude Oil Futures',
'QMZ21.NYM': 'E-mini Crude Oil Futures',
'QMN22.NYM': 'E-mini Crude Oil Futures',
'QC9.F': 'CRED. SAISON CO.LTD',
'QMH22.NYM': 'E-mini Crude Oil Futures',
'QMG22.NYM': 'E-mini Crude Oil Futures',
'QMV21.NYM': 'E-mini Crude Oil Futures',
'QMF22.NYM': 'E-mini Crude Oil Futures',
'QMK22.NYM': 'E-mini Crude Oil Futures',
'QC9.MU': 'CRED. SAISON CO.LTD',
'QNW.BE': 'REAL ESTATE CREDIT INVTS',
'QMZ22.NYM': 'E-mini Crude Oil Futures',
'QC9.DU': 'CRED. SAISON CO.LTD',
'QMM22.NYM': 'E-mini Crude Oil Futures',
'QMZ24.NYM': 'E-mini Crude Oil Futures',
'QQQ3.MI': 'WISDOMTREE NASDAQ 100 3X DAILY',
'QQQS.MI': 'WISDOMTREE NASDAQ 100 3X DAILY',
'QHH.F': 'DAI-ICHI LIFE HOLDINGS',
'QD7N.DE': 'INAV DBXT DAX 1C SEK',
'QHH.SG': 'Dai-Ichi Life Holdings Inc. Reg',
'QHH.BE': 'DAI-ICHI LIFE HOLDINGS',
'QHH.MU': 'DAI-ICHI LIFE HOLDINGS',
'Q00546.MI': 'LQ TRACKER ICE ECX FUT DEC22 22',
'QGZ21.NYM': 'E-mini Natural Gas Futures',
'QIZ21.CMX': 'E-mini Silver Futures',
'QOZ21.CMX': 'E-mini Gold Futures',
'QED': 'IQ Hedge Event-Driven Tracker E',
'QTUM': 'Defiance Quantum ETF',
'QDEF': 'FlexShares Quality Dividend Def',
'QQH': 'HCM Defender 100 Index ETF',
'QEH': 'None',
'QDEM': 'None',
'QEM': 'None',
'QC7.SI': 'Q&M Dental',
'QMBN.BE': 'Q+M DENTAL GROUP SING.LTD',
'QMBN.F': 'Q+M DENTAL GROUP SING.LTD',
'QEP': 'None',
'QXR2.F': 'DESERT GOLD VENTURES',
'QXR2.BE': 'DESERT GOLD VENTURES',
'QM01.SG': 'Desert Mountain Energy Corp. Re',
'QXR2.MU': 'DESERT GOLD VENTURES',
'QES': 'None',
'QDEU': 'None',
'QLVD': 'FlexShares Developed Markets ex',
'QGMD.QA': 'Qatari German for Medical Devic',
'QLDN.F': 'ELYSEE DEVELOPMENT',
'QLDN.BE': 'ELYSEE DEVELOPMENT',
'QRET.TO': 'MACKENZIE DEV MKTS REAL ESTATE',
'QDF': 'FlexShares Quality Dividend Ind',
'QDI.F': 'QUEST DIAGNOSTICS  DL-',
'QDI.DE': 'QUEST DIAGNOSTICS  DL-',
'QDI.BE': 'QUEST DIAGNOSTICS  DL-',
'QDI.MU': 'QUEST DIAGNOSTICS  DL-',
'QDI.SG': 'QUEST DIAGNOSTICS INC. Register',
'Q1UE34.SA': 'QUEST DIAGNODRN',
'QDI.DU': 'QUEST DIAGNOSTICS  DL-',
'QID': 'ProShares UltraShort QQQ',
'QFIN': '360 DigiTech',
'QUINT.BO': 'QUINT DIGITAL MEDIA LIMITED',
'QUANTDIA.BO': 'QUANTUM DIGITAL VISION (INDIA)',
'QFID.MI': 'QF IMMOBILIARE DINAMICO',
'QQQE': 'Direxion NASDAQ-100 Equal Weigh',
'QQQ.MX': 'INVESCO QQQ TRUST QQQ USD DIS',
'QBIT.SW': 'LY Disruptive Tech ESG Filt',
'QDIV.SW': 'iSh MSCI USA QualDiv USD Dis',
'QDIV': 'Global X S&P 500 Quality Divide',
'QDFD.AS': 'FlexShares DM Div',
'QDVIX': 'Quality Dividend Fund- Institut',
'QDVX.SG': 'iShares MSCI Europe Quality Div',
'QJQ.MU': 'ISS AS  DK 1',
'QJQ.BE': 'ISS AS  DK 1',
'QJQ.F': 'ISS AS  DK 1',
'QDVR.DE': 'ISIV-MSCIUSASRI U.ETF DLA',
'QDV7.MU': 'ISH3-I.JPM.EMLGB.UETF DLA',
'QDVR.F': 'ISIV-MSCIUSASRI U.ETF DLA',
'QDV8.MU': 'ISV-I.JPM.DLEMCB.UETF DLA',
'QDVR.BE': 'ISIV-MSCIUSASRI U.ETF DLA',
'QDVR.DU': 'ISIV-MSCIUSASRI U.ETF DLA',
'QDLC': 'QUADLOGIC CONTROLS CORP',
'QDVD.DE': 'I2-I.MSCI USA QD.UETF DLD',
'QDVP.DE': 'ISIV-US MO.B.SE.U.ETF DLD',
'QDVD.BE': 'I2-I.MSCI USA QD.UETF DLD',
'QDVP.F': 'ISIV-US MO.B.SE.U.ETF DLD',
'QDVD.F': 'I2-I.MSCI USA QD.UETF DLD',
'QDVP.BE': 'ISIV-US MO.B.SE.U.ETF DLD',
'QDVP.DU': 'ISIV-US MO.B.SE.U.ETF DLD',
'QDV2.MU': 'ISHSIV-E.M.US.VFU ETF DLD',
'QDVD.DU': 'I2-I.MSCI USA QD.UETF DLD',
'QVFD.AS': 'FlexShares DM Vol',
'QIFF12.SA': 'FII QUATA   DM   98',
'QQQA': 'ProShares Nasdaq-100 Dorsey Wri',
'QQD': 'Simplify Nasdaq 100 PLUS Downsi',
'QCOM34.SA': 'QUALCOMM    DRN',
'Q1RV34.SA': 'QORVO INC   DRN',
'QNT2.SG': 'Quantum Corp. Reg.Share of DSSG',
'QQQX': 'Nuveen NASDAQ 100 Dynamic Overw',
'QDYN': 'FlexShares Quality Dynamic Inde',
'QDMSIX': 'QS LM Dynamic Multi-Strat VIT P',
'QDMSTX': 'QS LM Dynamic Multi-Strat VIT P',
'Q5T.SI': 'Far East HTrust',
'QEFA': 'SPDR MSCI EAFE StrategicFactors',
'QOEG': 'QUALITY ONLINE EDUCATION GROUP',
'QDVC.SG': 'iShares Edge MSCI USA Size Fact',
'QDVI.SG': 'iShares Edge MSCI USA Value Fac',
'QSV.MU': 'EDENRED  EO 2',
'QSV.BE': 'EDENRED  EO 2',
'QDVB.SG': 'iShares Edge MSCI USA Quality F',
'QDVA.SG': 'iShares Edge MSCI USA Momentum',
'QSV.F': 'EDENRED  EO 2',
'QSV.DU': 'EDENRED  EO 2',
'Q0UG.Z': 'STX GL1800 EE TECH.PR USD',
'Q0S2.Z': 'STX GL1800 EE.A+PT.PR USD',
'Q0UJ.Z': 'STX GL1800 EE.UTIL PR USD',
'Q0UA.Z': 'STX GL1800 EE.INSU.PR USD',
'Q0S5.Z': 'STX GL1800 EE.CHEM.PR USD',
'Q0S9.Z': 'STX GL1800 EE.H.C. PR USD',
'Q0UB.Z': 'STX GL1800 EE.MEDI.PR USD',
'Q0S4.Z': 'STX GL1800 EE.B.RE.PR USD',
'Q0UI.Z': 'STX GL1800 EE.T+LE.PR USD',
'Q0S0.Z': 'STX GL1800 EE.IG+S.PR USD',
'Q0UH.Z': 'STX GL1800 EE.TELE.PR USD',
'Q0UF.Z': 'STX GL1800 EE RET. PR USD',
'Q0S7.Z': 'STX GL1800 EE.FI.S.PR USD',
'Q0S3.Z': 'STX GL1800 EE.BANK.PR USD',
'Q0S6.Z': 'STX GL1800 EE.CO+M.PR USD',
'QFP.F': 'ELEMENT 25 LTD',
'Q3S.Z': 'STXE TM EL.+EL.EQ. PR.USD',
'Q3T.Z': 'STXE TM EL.+EL.EQ. RE.EUR',
'QFP.MU': 'ELEMENT 25 LTD',
'QFP.BE': 'ELEMENT 25 LTD',
'Q3R.Z': 'STXE TM EL.+EL.EQ. PR.EUR',
'Q3U.Z': 'STXE TM EL.+EL.EQ. RE.USD',
'QEMM': 'SPDR MSCI Emerging Markets Stra',
'QLVE': 'FlexShares Emerging Markets  Qu',
'QDVS.SG': 'iShares Sustainable MSCI Emergi',
'QEBL.TO': 'MACKENZIE EMERGING MKTS LOCAL C',
'QEGY': 'QUANTUM ENERGY INC',
'QEC.OL': 'QUESTERRE ENERGY',
'QSEP': 'QS ENERGY INC',
'QDVF.SG': 'iShares S&P 500 Energy Sector U',
'QE1.MU': 'QUESTERRE ENERGY CORP. A',
'QK5.SG': 'Chip Eng Seng Corp. Ltd. Regist',
'QIA.DE': 'QIAGEN NV  EO -',
'QS3.F': 'SOLOCAL GROUP  EO 1',
'QIA.BE': 'QIAGEN NV  EO -',
'QIA.HM': 'QIAGEN NV  EO -',
'QU71.BE': 'LAVIDE HOLDING NV  EO 2',
'QTL.BE': 'LUMIBIRD S.A. INH.  EO 1',
'QDVL.SG': 'iShares II PLC ? iShares EO Cor',
'QS3.BE': 'SOLOCAL GROUP  EO 1',
'QIA.MU': 'QIAGEN NV  EO -',
'QIA.F': 'QIAGEN NV  EO -',
'QIA.DU': 'QIAGEN NV  EO -',
'QIA.HA': 'QIAGEN NV  EO -',
'QD70.DE': 'I.X.S+P500 2X I.D.S.1C EO',
'QTL.F': 'LUMIBIRD S.A. INH.  EO 1',
'Q8E.Z': 'STX.EU.400P.+H.G.IN.NR EO',
'QD7I.DE': 'I.XTRA.ESTX50 1C EO',
'Q8C.Z': 'STX.EU.400P.+H.G.IN.PR EO',
'QD71.DE': 'I.X.S+P500 2X L.D.S.1C EO',
'QQQ': 'Invesco QQQ Trust',
'QUU-U.TO': 'MACKENZIE US LARGE CAP EQTY IND',
'QAH.TO': 'MACKENZIE US LARGE CAP EQTY IDX',
'QQEW': 'First Trust NASDAQ-100 Equal We',
'QDFD.L': 'FLEXSHARES ICAV FLEXSHARES EQUI',
'QIVCX': 'Invesco International Equity Fu',
'QUU.TO': 'MACKENZIE US LARGE CAP EQUITY I',
'QDX.TO': 'MACKENZIE INTERNATIONAL EQUITY',
'QIVAX': 'Invesco International Equity Fu',
'QIVYX': 'Invesco International Equity Fu',
'QIVIX': 'Invesco International Equity Fu',
'QUS': 'SPDR MSCI USA StrategicFactors',
'QESP': 'None',
'Q7J.Z': 'ESTX TM SFTW.SERVS PR.USD',
'Q2E.Z': 'ESTX RETAIL RE.USD',
'Q3D.Z': 'ESTX TM RETAIL PR.EUR',
'Q19.Z': 'ESTX P.H.GD. PR.USD',
'Q7G.Z': 'ESTX TM PHRM.BIO.RE.USD',
'Q7H.Z': 'ESTX TM SFTW.SERVS PR.EUR',
'Q7K.Z': 'ESTX TM SFTW.SERVS RE.EUR',
'Q9R.F': 'SUNLIGHT REAL EST. UTS',
'Q9R.BE': 'SUNLIGHT REAL EST. UTS',
'Q6N.Z': 'ESTX TM HSH.GD.RE.USD',
'Q7E.Z': 'ESTX TM PHRM.BIO.PR.USD',
'Q7A.Z': 'ESTX TM PRS.GDS.PR.USD',
'Q7F.Z': 'ESTX TM PHRM.BIO.RE.EUR',
'Q6Q.Z': 'ESTX TM IND.MT.PR.USD',
'Q2B.Z': 'ESTX P.H.GD. RE.USD',
'Q7D.Z': 'ESTX TM PHRM.BIO.PR.EUR',
'Q7Q.Z': 'ESTX TM TECH.HW.EQ.RE.USD',
'Q6R.Z': 'ESTX TM IND.MT.RE.EUR',
'Q6S.Z': 'ESTX TM IND.MT.RE.USD',
'Q5X.Z': 'ESTX TM E.E.E.RE.EUR',
'Q6C.Z': 'ESTX TM GEN. IND. PR.USD',
'Q16.Z': 'ESTX TR. + LS PR.USD',
'Q5Y.Z': 'ESTX TM E.E.E.RE.USD',
'Q54.Z': 'ESTX TM GAS WT PR.USD',
'Q6D.Z': 'ESTX TM GEN. IND. RE.EUR',
'Q3E.Z': 'ESTX TM RETAIL PR.USD',
'Q17.Z': 'ESTX TR. + LS RE.EUR',
'Q2C.Z': 'ESTX RETAIL PR.USD',
'Q6T.Z': 'ESTX TM LFE.IN.PR.EUR',
'Q55.Z': 'ESTX TM GAS WT RE.EUR',
'Q25.Z': 'ESTX TM TRAV.+LEIS.PR.EUR',
'Q6E.Z': 'ESTX TM GEN. IND. RE.USD',
'Q2A.Z': 'ESTX P.H.GD. RE.EUR',
'Q7P.Z': 'ESTX TM TECH.HW.EQ.RE.EUR',
'Q6L.Z': 'ESTX TM HSH.GD.PR.USD',
'Q6B.Z': 'ESTX TM GEN. IND. PR.EUR',
'Q27.Z': 'ESTX TM TRAV.+LEIS.RE.EUR',
'Q28.Z': 'ESTX TM TRAV.+LEIS.RE.USD',
'Q6V.Z': 'ESTX TM LFE.IN.RE.EUR',
'Q2D.Z': 'ESTX RETAIL RE.EUR',
'Q7B.Z': 'ESTX TM PRS.GDS.RE.EUR',
'Q3F.Z': 'ESTX TM RETAIL RE.EUR',
'Q6M.Z': 'ESTX TM HSH.GD.RE.EUR',
'Q5W.Z': 'ESTX TM E.E.E.PR.USD',
'Q7C.Z': 'ESTX TM PRS.GDS.RE.USD',
'Q69.Z': 'ESTX TM PRS.GDS.PR.EUR',
'Q26.Z': 'ESTX TM TRAV.+LEIS.PR.USD',
'Q7N.Z': 'ESTX TM TECH.HW.EQ.PR.USD',
'Q18.Z': 'ESTX TR. + LS RE.USD',
'Q6K.Z': 'ESTX TM HSH.GD.PR.EUR',
'Q6U.Z': 'ESTX TM LFE.IN.PR.USD',
'Q5V.Z': 'ESTX TM E.E.E.PR.EUR',
'Q3G.Z': 'ESTX TM RETAIL RE.USD',
'Q6P.Z': 'ESTX TM IND.MT.PR.EUR',
'Q56.Z': 'ESTX TM GAS WT RE.USD',
'Q7M.Z': 'ESTX TM TECH.HW.EQ.PR.EUR',
'Q6W.Z': 'ESTX TM LFE.IN.RE.USD',
'QQQJ': 'Invesco NASDAQ Next Gen 100 ETF',
'QQQM': 'Invesco NASDAQ 100 ETF',
'QQQN': 'VictoryShares Nasdaq Next 50 ET',
'QQC-F.TO': 'INVESCO NASDAQ 100 INDEX ETF',
'QTIP.NE': 'MACKENZIE US TIPS INDEX ETF (CA',
'QQC.TO': 'INVESCO NASDAQ 100 INDEX ETF',
'QUAL.AX': 'VE WD QUAL ETF UNITS',
'QULL': 'ETRACS 2x Leveraged MSCI US Qua',
'QNT-ETH': 'Quant ETH',
'QMIX.AX': 'SPDR QMIX ETF UNITS',
'QRK-ETH': 'Quark ETH',
'QHAL.AX': 'VEQUAL HDG ETF UNITS',
'QI8K.BE': 'ISHS INC.-MSCI RUSSIA ETF',
'QSML.AX': 'VE QSML ETF UNITS',
'QDV5.SG': 'iShares MSCI India UCITS ETF',
'QTUM-ETH': 'Qtum ETH',
'QRL-ETH': 'QuantumResistantLedger ETH',
'QETF.QA': 'QE Index ETF',
'QVMP.SG': 'Invesco S&P 500 QVM UCITS ETF',
'QURE': 'uniQure N.V.',
'QDVV.DU': 'ISHS VI-MSCI EURO.MID CAP',
'QDVV.MU': 'ISHS VI-MSCI EURO.MID CAP',
'QD7K.DE': 'I.XTRA.MSCI EURO.1C SEK',
'QURS': 'None',
'QURT': 'QUARTA RAD INC',
'QEVOX': 'Quantified Evolution Plus Fund',
'QGJ.SG': 'Evercore Inc. Registered Shs A',
'QGJ.F': 'EVERCORE  A DL -',
'QQXT': 'First Trust NASDAQ-100 Ex-Techn',
'QCLN.MX': 'FIRST TRUST EXCHANGE TRADED FUN',
'Q1X.Z': 'STXE600 EXUK TR+LE.RE USD',
'Q12.Z': 'STXE600 EXUK RETAI.PR EUR',
'QGOLDHALF.BO': 'QUANTUM GOLD FUND - EXCHANGE T',
'Q1W.Z': 'STXE600 EXUK TR+LE.RE EUR',
'Q1V.Z': 'STXE600 EXUK TR+LE.PR USD',
'Q14.Z': 'STXE600 EXUK RETAI.RE EUR',
'Q1U.Z': 'STXE600 EXUK TR+LE.PR EUR',
'Q0U2.Z': 'STX GL1800 EX AM. PR.USD',
'Q0U4.Z': 'STX GL1800 EX EUR. PR USD',
'Q15.Z': 'STXE600 EXUK RETAI.RE USD',
'Q13.Z': 'STXE600 EXUK RETAI.PR USD',
'QUAL': 'iShares MSCI USA Quality Factor',
'QDVQ.BE': 'ISHSIV-FALL.A.H.Y.C.BDDLD',
'QDVQ.DE': 'ISHSIV-FALL.A.H.Y.C.BDDLD',
'QDVQ.DU': 'ISHSIV-FALL.A.H.Y.C.BDDLD',
'QDVQ.F': 'ISHSIV-FALL.A.H.Y.C.BDDLD',
'QDVQ.MU': 'ISHSIV-FALL.A.H.Y.C.BDDLD',
'QNIFTY.NS': 'QUANTUM MUTUAL FD',
'QISGX': 'Federated Hermes MDT Small Cap',
'QASGX': 'Federated Hermes MDT Small Cap',
'QLSGX': 'Federated Hermes MDT Small Cap',
'QISCX': 'Federated Hermes MDT Small Cap',
'QASCX': 'Federated Hermes MDT Small Cap',
'QLSCX': 'Federated Hermes MDT Small Cap',
'QOG22.CMX': 'E-mini Gold Futures',
'QBLGX': 'Federated Hermes MDT Large Cap',
'QALGX': 'Federated Hermes MDT Large Cap',
'QRLVX': 'Federated Hermes MDT Large Cap',
'QCSGX': 'Federated Hermes MDT Small Cap',
'QCSCX': 'Federated Hermes MDT Small Cap',
'QBLVX': 'Federated Hermes MDT Large Cap',
'QCLVX': 'Federated Hermes MDT Large Cap',
'QDVH.DE': 'ISHSV-S+P500 FIN.SECT.DLA',
'QNBFL.IS': 'QNB FINANS FINANSAL KIRALAMA',
'QNBFB.IS': 'QNB FINANSBANK',
'QFSL.BO': 'Quest Financial Services Ltd.',
'QGO.BO': 'QGO FINANCE LIMITED',
'QDVH.F': 'ISHSV-S+P500 FIN.SECT.DLA',
'QDVH.BE': 'ISHSV-S+P500 FIN.SECT.DLA',
'QDVH.MU': 'ISHSV-S+P500 FIN.SECT.DLA',
'QDVH.SG': 'iShares S&P 500 Financials Sect',
'QDVH.DU': 'ISHSV-S+P500 FIN.SECT.DLA',
'Q0UK.Z': 'STX GL1800 FIN.SER.PR USD',
'QTEC': 'First Trust NASDAQ-100-Technolo',
'QCLN.L': 'FIRST TRUST GLOBAL FUNDS PUBLIC',
'QTEC.MX': 'FIRST TRUST NASDAQ-100- TECH IN',
'QCLU.L': 'FIRST TRUST GLOBAL FUNDS PUBLIC',
'QDISX': 'Fisher Investments Institutiona',
'QDVSX': 'Fisher Investments Institutiona',
'QDIBX': 'Fisher Investments Institutiona',
'QDVBX': 'Fisher Investments Institutiona',
'QRTEP': 'Qurate Retail',
'QFITX': 'Quantified Tactical Fixed Incom',
'QUSOX': 'Pear Tree Polaris Foreign Value',
'QUSIX': 'Pear Tree Polaris Foreign Value',
'QFH.JO': 'Quantum Foods Hldgs Ltd',
'QFVOX': 'Pear Tree Polaris Foreign Value',
'QFVIX': 'Pear Tree Foreign Value Fund In',
'QFVRX': 'Pear Tree Polaris Foreign Value',
'QUSRX': 'Pear Tree Polaris Foreign Value',
'QAN.AX': 'QANTAS FPO',
'QHL.AX': 'QUICKSTEP FPO',
'QBE.AX': 'QBE INSUR. FPO',
'QPM.AX': 'QLDPACIFIC FPO',
'QUB.AX': 'QUBE FPO',
'QIP.AX': 'QANTMIP FPO',
'QTM.AX': 'QUANTHEGRP FPO',
'QML.AX': 'QMINES FPO',
'QEM.AX': 'QEMLIMITED FPO',
'QFE.AX': 'QUICKFEE FPO',
'QXR.AX': 'QXRESOURCE FPO',
'QVE.AX': 'QVEQUITIES FPO',
'QCLN.F': 'FTGF-FT NASD.C.E.G.E.U.E.',
'QCLN.DE': 'FTGF-FT NASD.C.E.G.E.U.E.',
'QCLN.MU': 'FTGF-FT NASD.C.E.G.E.U.E.',
'QDII1.FGI': 'FTSE Hong Kong Index',
'QCLN.DU': 'FTGF-FT NASD.C.E.G.E.U.E.',
'QCLN.BE': 'FTGF-FT NASD.C.E.G.E.U.E.',
'QFI.L': 'QUADRISE FUELS INTERNATIONAL PL',
'QFLS.QA': 'Qatar Fuel QPSC',
'QFLS@S.QA': 'Qatar Fuel QPSC',
'QMLFX': 'Quantified Market Leaders Fund',
'QSTFX': 'Quantified STF Fund - Investor',
'QRVLX': 'Queens Road Value Fund',
'QGIAX': 'Pear Tree Quality Fund Institut',
'QNIFTY.BO': 'QUANTUM MUTUAL FUND - QUANTUM',
'QBDSX': 'Quantified Managed Income Fund',
'QBDAX': 'Quantified Managed Income Fund',
'QMLAX': 'Quantified Market Leaders Fund',
'QUNR': 'Qunar Cayman Islands Limited -',
'QG=F': 'E-mini Natural Gas Futures',
'QI=F': 'E-mini Silver Futures',
'QU=F': 'E-mini RBOB Gasoline Futures',
'QGK23.NYM': 'E-mini Natural Gas Futures',
'QGN21.NYM': 'E-mini Natural Gas Futures',
'QGF22.NYM': 'E-mini Natural Gas Futures',
'QGK22.NYM': 'E-mini Natural Gas Futures',
'QGX21.NYM': 'E-mini Natural Gas Futures',
'QIU21.CMX': 'E-mini Silver Futures',
'QIN22.CMX': 'E-mini Silver Futures',
'QHN21.NYM': 'E-mini NY Harbor ULSD Futures',
'QOV21.CMX': 'E-mini Gold Futures',
'QIH22.CMX': 'E-mini Silver Futures',
'QGU21.NYM': 'E-mini Natural Gas Futures',
'QIN21.CMX': 'E-mini Silver Futures',
'QGV21.NYM': 'E-mini Natural Gas Futures',
'QUN21.NYM': 'E-mini RBOB Gasoline Futures',
'QH=F': 'E-mini NY Harbor ULSD Futures',
'QGTS.QA': 'Qatar Gas Transport Ltd QPSC',
'QGTS@S.QA': 'Qatar Gas Transport Ltd QPSC',
'Q32.Z': 'STXE TM GAS',
'Q30.Z': 'STXE TM GAS',
'Q31.Z': 'STXE TM GAS',
'Q3Z.Z': 'STXE TM GAS',
'QLT.L': 'QUILTER PLC ORD GBP0.07',
'QRK-GBP': 'Quark GBP',
'QSD.SI': '$ Resources Gbl',
'QNT-GBP': 'Quant GBP',
'QASH-GBP': 'QASH GBP',
'QTUM-GBP': 'Qtum GBP',
'QRL-GBP': 'QuantumResistantLedger GBP',
'QQJR.TO': 'INVESCO NASDAQ NEXT GEN 100 IND',
'QA4A.BE': 'GENTHERM INC. A',
'QA4A.SG': 'Gentherm Inc. Registered Shares',
'QA4A.F': 'GENTHERM INC. A',
'Q38.Z': 'STXE TM GEN. IND. PR.USD',
'Q37.Z': 'STXE TM GEN. IND. PR.EUR',
'Q39.Z': 'STXE TM GEN. IND. RE.EUR',
'Q4A.Z': 'STXE TM GEN. IND. RE.USD',
'QGI': 'None',
'QWTR': 'QUEST WATER GLOBAL INC',
'QINF.TO': 'MACKENZIE GLOBAL INFRASTRUCTURE',
'QCE.HM': 'GLOBAL PVQ SE',
'Q00C.Z': 'STX GLOBAL 1800 PR EUR',
'Q0UX.Z': 'STX GL1800 TRVL+LE.PR.USD',
'Q0UN.Z': 'STX GL1800 I.GDS+S.PR USD',
'Q0UT.Z': 'STX GL1800 RE.EST.PR USD',
'Q0UM.Z': 'STX GL1800 HEAL.C.PR USD',
'Q0UP.Z': 'STX GL1800 INSUR. PR USD',
'Q0UV.Z': 'STX GL1800 TECHN. PR.USD',
'Q0UE.Z': 'STX GL1800 EU R.ES.PR USD',
'Q0UU.Z': 'STX GL1800 RETAIL PR.USD',
'Q0U5.Z': 'STX GL1800 REITS PR.USD',
'Q0BX.Z': 'STX GL1800 CON.+MA.PR USD',
'Q0BV.Z': 'STX GL1800 BA.RES. PR USD',
'Q0UY.Z': 'STX GL1800 UTILIT. PR.USD',
'Q0UQ.Z': 'STX GL1800 MEDIA PR USD',
'Q0UW.Z': 'STX GL1800 TELECOM.PR.USD',
'QGR.V': 'Q GOLD RESOURCES LTD',
'QX9G.F': 'Q-GOLD RES',
'Q4H.Z': 'STXE TM HH GOODS RE.EUR',
'Q4G.Z': 'STXE TM HH GOODS PR.USD',
'QGRSF': 'Q2 GOLD RESOURCES INC',
'Q4J.Z': 'STXE TM HH GOODS RE.USD',
'QGLDF': 'Q-GOLD RESOURCES LTD',
'QGOLDHALF.NS': 'QUANTUM GOLD FUND',
'QX9G.BE': 'Q-GOLD RES',
'Q4F.Z': 'STXE TM HH GOODS PR.EUR',
'QUAD': 'Quad Graphics',
'QUAGR.IS': 'QUA GRANITE HAYAL YAPI',
'QGU.F': 'QUAD GRAPHICS INC. CL. A',
'QGU.SG': 'Quad Graphics Inc. Registered S',
'QRE': 'None',
'QFRA.BE': 'GREENLAND HK HLDGS HD-',
'QFRA.F': 'GREENLAND HK HLDGS HD-',
'QRM': 'None',
'QRON': 'QRONS INC',
'QTCOM.HE': 'Qt Group Oyj',
'QBIEY': 'QBE INSURANCE GROUP',
'QQ.L': 'QINETIQ GROUP PLC ORD 1P',
'QIAN': 'QIANSUI INTL GROUP CO LTD',
'QISI.QA': 'Qatar Islamic Insurance Group Q',
'QD4.F': 'QUANTUM HEALTH GROUP LTD.',
'QSS.SG': 'Sheng Siong Group Ltd Registere',
'QD4.SG': 'Quantum Health Group Ltd. Regis',
'QY6.BE': 'QINETIQ GROUP PLC LS -',
'QHI.BE': 'SHIMAO GROUP HLDGS HD-',
'QY6.MU': 'QINETIQ GROUP PLC LS -',
'QHI.SG': 'SHIMAO GROUP HOLDINGS LTD',
'QS2A.BE': 'SMITHS GROUP PLC LS -',
'QIGD.QA': 'Qatari Investors Group QPSC',
'QY6.DU': 'QINETIQ GROUP PLC LS -',
'QS2A.SG': 'Smiths Group PLC Registered Sha',
'QPA1.SG': 'Trisura Group Ltd. Registered S',
'QPA1.F': 'TRISURA GROUP LTD',
'QS2A.MU': 'SMITHS GROUP PLC LS -',
'QY6.F': 'QINETIQ GROUP PLC LS -',
'QHI.F': 'SHIMAO GROUP HLDGS HD-',
'QY6.SG': 'Qinetiq Group PLC Registered Sh',
'QRTE.VI': 'QURATE RETAIL GROUP INC',
'QS2A.F': 'SMITHS GROUP PLC LS -',
'QAGIX': 'Quaker Impact Growth Fund Insti',
'QLMLSX': 'QS Variable Moderate Growth Cla',
'QLMLTX': 'QS Variable Growth Class I',
'QBE.BE': 'QBE INSURANCE GRP',
'QBE.F': 'QBE INSURANCE GRP',
'QBE.DU': 'QBE INSURANCE GRP',
'QEV.BE': 'LEE KEE HLDGS LTD  HD-',
'QHI.MU': 'SHIMAO GROUP HLDGS HD-',
'QU4B.F': 'C C LAND HOLDINGS  HD-',
'QUICKHEAL.BO': 'Quick Heal Technologies Limite',
'QUICKHEAL.NS': 'QUICK HEAL TECHNOL',
'QY1.BE': 'NEXTGEN HEALTHC.  DL-',
'QCLGX': 'Federated Hermes MDT Large Cap',
'QILGX': 'Federated Hermes MDT Large Cap',
'QY1.F': 'NEXTGEN HEALTHC.  DL-',
'QCCO': 'QC HLDGS INC',
'QTS.BE': 'IQVIA HLDGS  DL-',
'QIS.BE': 'QUICKSTEP HLDGS LTD',
'QTS.F': 'IQVIA HLDGS  DL-',
'QTS.DE': 'IQVIA HLDGS  DL-',
'QJE.SG': 'Pan Pacific Intl Hldgs Corp. Re',
'QRL.DU': 'AURIZON HLDGS LTD',
'QTS.MU': 'IQVIA HLDGS  DL-',
'QTWO': 'Q2 Holdings',
'QCRH': 'QCR Holdings',
'QUIA.ST': 'QuiaPEG Pharmaceuticals Holding',
'QTX.L': 'QUARTIX HOLDINGS PLC ORD 1P',
'QHPF.BK': 'QUALITY HOUSES LEASEHOLD PROPER',
'QUEST.AT': 'QUEST HOLDING S.A.',
'QHOP.BK': 'QUALITY HOSPITALITY LEASEHOLD P',
'Q9J.BE': 'INLAND HOMES PLC',
'QCKSF': 'QUICKSTEP HOLDINGS LTD',
'QU4B.SG': 'C C Land Holdings Ltd. Reg.Cons',
'QTS.SG': 'IQVIA Holdings Inc. Registered',
'QRI.AX': 'QUAL RE IF UNITS',
'Q0F.SI': 'IHH',
'QDIV.L': 'ISHARES II PLC ISHRS MSCI USA Q',
'QDVD.SG': 'iShares II PLC ? iShares MSCI U',
'QVMP.F': 'IMIII-I.S+P 500 QVM D',
'QFVIG.MI': 'QF VALORE IMM GLOBAL',
'QSVIX': 'Quaker Small/Mid-Cap Impact Val',
'QVMP.MU': 'IMIII-I.S+P 500 QVM D',
'QUSVX': 'Quaker Small/Mid-Cap Impact Val',
'QFIMM.MI': 'QF IMMOBILIUM 2001',
'QVMP.DU': 'IMIII-I.S+P 500 QVM D',
'QBI.VI': 'Qbasis i Trend Index in EUR',
'QDV5.DE': 'ISHSIV-MSCI INDIA UC.ETF',
'QK9.SI': 'IS MS INDIA S$D',
'QUASAR.BO': 'QUASAR INDIA LTD',
'QUEST.BO': 'QUEST SOFTECH (INDIA) LTD',
'QDV5.BE': 'ISHSIV-MSCI INDIA UC.ETF',
'QDV5.F': 'ISHSIV-MSCI INDIA UC.ETF',
'QDV5.DU': 'ISHSIV-MSCI INDIA UC.ETF',
'QF9.F': 'MULTI INDOCITRA  RP 100',
'QF9.SG': 'Multi Indocitra TBK Registered',
'QU5A.SG': 'Padaeng Industry PCL Reg. Share',
'QIMD.QA': 'Qatar Industrial Manufacturing',
'QIS.V': 'Quorum Information Technologies',
'QIFTF': 'QUORUM INFORMATION TECHNOLOGIES',
'QDVE.SG': 'iShares S&P 500 Information Tec',
'QING': 'QINGDAO FOOTWEAR INC',
'QZG2.MU': 'ZEUS STRATEGIE FUND INH.',
'QZG2.BE': 'ZEUS STRATEGIE FUND INH.',
'QZG2.DU': 'ZEUS STRATEGIE FUND INH.',
'QZG2.HM': 'ZEUS STRATEGIE FUND INH.',
'QLIS': 'QUALIS INNOVATIONS INC',
'QNT-INR': 'Quant INR',
'QTUM-INR': 'Qtum INR',
'QRL-INR': 'QuantumResistantLedger INR',
'QRK-INR': 'Quark INR',
'QASH-INR': 'QASH INR',
'QATI.QA': 'Qatar Insurance QSPC',
'QBE.SG': 'QBE INSURANCE GROUP LTD. Regist',
'QATI@S.QA': 'Qatar Insurance QSPC',
'QBE.HM': 'QBE INSURANCE GRP',
'Q4W.Z': 'STXE TM LIFE INS. RE.USD',
'QNTIX': 'Meeder Quantex Fund - Instituti',
'Q4V.Z': 'STXE TM LIFE INS. RE.EUR',
'Q4U.Z': 'STXE TM LIFE INS. PR.USD',
'Q4T.Z': 'STXE TM LIFE INS. PR.EUR',
'QEBR': 'VIRTUAL MEDICAL INTERNATIONAL I',
'QIIK.QA': 'Qatar International Islamic Ban',
'QIVNX': 'Invesco International Equity Fu',
'QISOX': 'Pear Tree Polaris International',
'QISRX': 'Pear Tree Polaris International',
'QS9.SI': 'G Invacom',
'QOIS.QA': 'Qatar Oman Investment QPSC',
'QVMP.DE': 'INVESCOM3 S+P 500 QVM A',
'QVMP.BE': 'INVESCOM3 S+P 500 QVM A',
'QDVE.DE': 'ISHSV-S+500INF.T.SECT.DLA',
'QDVA.DE': 'ISHSIV-E.MSCI USA M.F.DLA',
'QDVF.DE': 'ISHSV-S+P500ENER.SECT.DLA',
'QDVW.DE': 'ISHSII-MSCI WL.QUA.DV.DLD',
'QDVG.DE': 'ISHSV-S+P500H.CA.SECT.DLA',
'QDVI.DE': 'ISHSIV-E.MSCI USA VAL.FA.',
'QDVB.DE': 'ISHSIV-E.MSCI USA QUAL.F.',
'QDVK.DE': 'ISHSV-S+P500C.D.SECT.DL A',
'QDVE.F': 'ISHSV-S+500INF.T.SECT.DLA',
'QDVS.DE': 'ISHSIV-SUS.M.EM.MK.SRI DL',
'QDVX.DE': 'ISHSII-MSCI EU.QUA.DV.EOD',
'QDVK.F': 'ISHSV-S+P500C.D.SECT.DL A',
'QDVS.DU': 'ISHSIV-SUS.M.EM.MK.SRI DL',
'QDVE.DU': 'ISHSV-S+500INF.T.SECT.DLA',
'QDVF.F': 'ISHSV-S+P500ENER.SECT.DLA',
'QDVA.MU': 'ISHSIV-E.MSCI USA M.F.DLA',
'QDV3.MU': 'ISHSIV-E.MSCI W.VAL.F.DLD',
'QDVX.F': 'ISHSII-MSCI EU.QUA.DV.EOD',
'QDVW.SG': 'iShares MSCI World QualityDivid',
'QDVC.DE': 'ISHSIV-E.MSCI USA SIZE.F.',
'QDVX.DU': 'ISHSII-MSCI EU.QUA.DV.EOD',
'QDVW.BE': 'ISHSII-MSCI WL.QUA.DV.DLD',
'QDV9.MU': 'ISH.7-C.MSCI E.U.E LSD',
'QDVA.F': 'ISHSIV-E.MSCI USA M.F.DLA',
'QDVW.F': 'ISHSII-MSCI WL.QUA.DV.DLD',
'QDVW.MU': 'ISHSII-MSCI WL.QUA.DV.DLD',
'QDVE.MU': 'ISHSV-S+500INF.T.SECT.DLA',
'QDVF.BE': 'ISHSV-S+P500ENER.SECT.DLA',
'QDVE.BE': 'ISHSV-S+500INF.T.SECT.DLA',
'QDVB.BE': 'ISHSIV-E.MSCI USA QUAL.F.',
'QDVB.DU': 'ISHSIV-E.MSCI USA QUAL.F.',
'QDVC.DU': 'ISHSIV-E.MSCI USA SIZE.F.',
'QDV1.MU': 'ISHSVI-E.S+P500MIN.V.DL D',
'QDVN.SG': 'iShares Sustainable MSCI Japan',
'QDVK.MU': 'ISHSV-S+P500C.D.SECT.DL A',
'QDVX.MU': 'ISHSII-MSCI EU.QUA.DV.EOD',
'QDVI.F': 'ISHSIV-E.MSCI USA VAL.FA.',
'QDVG.DU': 'ISHSV-S+P500H.CA.SECT.DLA',
'QDVG.BE': 'ISHSV-S+P500H.CA.SECT.DLA',
'QDVF.DU': 'ISHSV-S+P500ENER.SECT.DLA',
'QDVK.BE': 'ISHSV-S+P500C.D.SECT.DL A',
'QDVI.MU': 'ISHSIV-E.MSCI USA VAL.FA.',
'QDVS.F': 'ISHSIV-SUS.M.EM.MK.SRI DL',
'QDVW.DU': 'ISHSII-MSCI WL.QUA.DV.DLD',
'QUAL.MX': 'ISHARES TRUST MSCI USA QUALITY',
'QDVS.BE': 'ISHSIV-SUS.M.EM.MK.SRI DL',
'QDVR.SG': 'iShares Sustainable MSCI USA SR',
'QDVF.MU': 'ISHSV-S+P500ENER.SECT.DLA',
'QDVC.MU': 'ISHSIV-E.MSCI USA SIZE.F.',
'QDVG.MU': 'ISHSV-S+P500H.CA.SECT.DLA',
'QDVB.F': 'ISHSIV-E.MSCI USA QUAL.F.',
'QDVG.F': 'ISHSV-S+P500H.CA.SECT.DLA',
'QDVI.BE': 'ISHSIV-E.MSCI USA VAL.FA.',
'QDVA.BE': 'ISHSIV-E.MSCI USA M.F.DLA',
'QDVI.DU': 'ISHSIV-E.MSCI USA VAL.FA.',
'QDVA.DU': 'ISHSIV-E.MSCI USA M.F.DLA',
'QDVX.BE': 'ISHSII-MSCI EU.QUA.DV.EOD',
'QDVK.DU': 'ISHSV-S+P500C.D.SECT.DL A',
'QDVC.F': 'ISHSIV-E.MSCI USA SIZE.F.',
'QDVB.MU': 'ISHSIV-E.MSCI USA QUAL.F.',
'QDVN.BE': 'ISIV-MSCI J.SRIEH.U.ETF A',
'QDVN.DE': 'ISIV-MSCI J.SRIEH.U.ETF A',
'QDVN.F': 'ISIV-MSCI J.SRIEH.U.ETF A',
'QDVN.MU': 'ISIV-MSCI J.SRIEH.U.ETF A',
'QDVN.DU': 'ISIV-MSCI J.SRIEH.U.ETF A',
'QFOPI.MI': 'QF OPPORTUNITA ITALIA',
'QD7L.DE': 'I.XTRA.MSCI JAP.1C SEK',
'QTUM-JPY': 'Qtum JPY',
'QRL-JPY': 'QuantumResistantLedger JPY',
'QNT-JPY': 'Quant JPY',
'QRK-JPY': 'Quark JPY',
'QASH-JPY': 'QASH JPY',
'QPJ.F': 'KEWPIE CORP.',
'QPJ.BE': 'KEWPIE CORP.',
'QTUM-KRW': 'Qtum KRW',
'QRK-KRW': 'Quark KRW',
'QRL-KRW': 'QuantumResistantLedger KRW',
'QNT-KRW': 'Quant KRW',
'QASH-KRW': 'QASH KRW',
'QGY.BE': 'PROPHASE LABS INC. DL-001',
'QARP': 'Xtrackers Russell 1000 US Quali',
'QLMAEX': 'Legg Mason/QS Moderate Model Po',
'QLMAFX': 'Legg Mason/QS Moderate Model Po',
'Q2H.Z': 'STXE TM TRV.+LEIS. RE EUR',
'Q4S.Z': 'STXE TM LEIS.GOODS RE USD',
'Q4R.Z': 'STXE TM LEIS.GOODS RE EUR',
'Q4Q.Z': 'STXE TM LEIS.GOODS PR USD',
'Q2F.Z': 'STXE TM TRV.+LEIS. PR EUR',
'Q2G.Z': 'STXE TM TRV.+LEIS. PR USD',
'Q2J.Z': 'STXE TM TRV.+LEIS. RE USD',
'Q4P.Z': 'STXE TM LEIS.GOODS PR EUR',
'QLIK': 'Qlik Technologies Inc.',
'QTNT': 'Quotient Limited',
'QUADRANT.BO': 'QUADRANT TELEVENTURES LIMITED',
'QEG2.BE': 'TERN PLC  LS-',
'QIG.F': 'SIG PLC  LS-',
'QS2A.DU': 'SMITHS GROUP PLC LS -',
'Q1H.Z': 'STXE 600 TR.+ LS. PR.USD',
'Q1G.Z': 'STXE 600 TR.+ LS. PR.EUR',
'QAB.F': 'QUIZ PLC  LS -',
'QIG.SG': 'SIG PLC Registered Shares LS -',
'Q1K.Z': 'STXE 600 TR.+ LS. RE.USD',
'QIG.BE': 'SIG PLC  LS-',
'QIG.DU': 'SIG PLC  LS-',
'Q1J.Z': 'STXE 600 TR.+ LS. RE.EUR',
'QEG2.F': 'TERN PLC  LS-',
'QD77.DE': 'I.X.S+P500 2X I.D.S.1C LS',
'QD74.DE': 'I.XTRA.L.DAX D.S.1C LS',
'QD75.DE': 'I.XTRA.S.D.X2I.D.S.1C LS',
'QLTB': 'None',
'QLTC': 'None',
'QLTI': 'QLT Inc.',
'QTM': 'None',
'QTS': 'QTS Realty Trust',
'QLTS': 'None',
'QTT': 'Qutoutiao Inc.',
'QLTY': 'None',
'QF8.F': 'MANDALA MULTIFIN.  RP100',
'QF8.BE': 'MANDALA MULTIFIN.  RP100',
'QYOU.V': 'QYOU MEDIA INC',
'QYOUF': 'QYOU MEDIA INC',
'QMDT': 'QUICK-MED TECHNOLOGIES INC',
'QMED': 'Q-MED INC',
'QTNA.SG': 'Titan Medical Inc. Registered S',
'QQ.CN': 'Quizam Media',
'QFMRB.MI': 'QF MEDIOLANUM RE B',
'QFMRA.MI': 'QF MEDIOLANUM RE A',
'QTNA.DU': 'TITAN MEDICAL INC.',
'QTNA.F': 'TITAN MEDICAL INC.',
'QTNA.BE': 'TITAN MEDICAL INC.',
'Q4K.Z': 'STXE TM IND. MET. PR EUR',
'Q4L.Z': 'STXE TM IND. MET. PR USD',
'Q4M.Z': 'STXE TM IND. MET. RE EUR',
'Q4N.Z': 'STXE TM IND. MET. RE USD',
'QMEX': 'None',
'QSMG': 'QUEST MGMT INC',
'QBI.HM': 'Q2M MGMT.BERAT.AG',
'QRMLF': 'QUEST RARE MINERALS LTD',
'QM3.SG': 'Nova Minerals Ltd. Registered S',
'QYM.SG': 'Soc.Quimica y Min.de Chile SA R',
'QM3.F': 'NOVA MINERALS',
'QYM.DU': 'SOC. QUIMICA MIN.ADR B 1',
'QYM.F': 'SOC. QUIMICA MIN.ADR B 1',
'QM3.BE': 'NOVA MINERALS',
'QYM.BE': 'SOC. QUIMICA MIN.ADR B 1',
'QYM.MU': 'SOC. QUIMICA MIN.ADR B 1',
'QMIN': 'None',
'QGI.F': 'MITRA ADIPERKASA  RP 500',
'QIN.F': 'QINGLING MOTORS CO. H YC1',
'QIN.MU': 'QINGLING MOTORS CO. H YC1',
'QIN.HA': 'QINGLING MOTORS CO. H YC1',
'QIN.SG': 'Qingling Motors Co. Ltd. Regist',
'QIN.BE': 'QINGLING MOTORS CO. H YC1',
'QIN.DU': 'QINGLING MOTORS CO. H YC1',
'QZM.V': 'QUARTZ MOUNTAIN RESOURCES LTD',
'QWLD': 'SPDR MSCI World StrategicFactor',
'QNNS.QA': 'Qatar Navigation QPSC',
'QNNS@S.QA': 'Qatar Navigation QPSC',
'QY1.SG': 'NextGen Healthcare Inc. Registe',
'QSX1.F': 'NEARMAP LTD',
'QUAL3.SA': 'QUALICORP   ON      NM',
'Q1N.Z': 'STXE 600 P.H.GD. NR EUR',
'QGEN.VI': 'QIAGEN NV',
'QU5A.F': 'PADAENG IND. -NVDR- BA 10',
'QUIK.TA': 'QUIK SUPER ONLINE',
'QSOA.F': 'SURFACE ONCOLOGY DL-',
'QSOA.BE': 'SURFACE ONCOLOGY DL-',
'QXT.L': 'QUIXANT PLC ORD 0.1P',
'QUIZ.L': 'QUIZ PLC ORD 0.3P',
'QSPMX': 'Quantified Pattern Recognition',
'QPX.F': 'PAREX RESOURCES INC.',
'QJE.F': 'PAN PACIFIC INT.HLDG.CORP',
'QPE.SG': 'PEC Ltd. Registered Shares o.N.',
'Q5E.Z': 'STXE TM PERS.GODDS PR USD',
'Q5D.Z': 'STXE TM PERS.GODDS PR EUR',
'QISIX': 'Pear Tree Polaris International',
'QPE.MU': 'PEC LTD.',
'QPE.F': 'PEC LTD.',
'QBNAX': 'Pear Tree Polaris Small Cap Fun',
'Q5G.Z': 'STXE TM PERS.GODDS RE USD',
'Q5F.Z': 'STXE TM PERS.GODDS RE EUR',
'QPT.V': 'QUEST PHARMATECH INC.',
'QPTFF': 'QUEST PHARMATECH INC',
'QIWI': 'QIWI plc',
'QIWI.ME': 'QIWI PLC',
'QPR1V.HE': 'QPR Software Plc',
'QLT.JO': 'Quilter Plc',
'QIW.SG': 'QIWI PLC Reg.Sh.B(Spons.ADRs)1/',
'QXT-GB.AQ': 'QUIXANT PLC',
'QHD.F': 'QINHUANGDAO PORT  H YC 1',
'QHD.MU': 'QINHUANGDAO PORT  H YC 1',
'QFG.BR': 'QUESTFOR GR-PRICAF',
'QB7.DE': 'QUIRIN PRIVATBK  O.N.',
'QB7.HM': 'QUIRIN PRIVATBK  O.N.',
'QB7.DU': 'QUIRIN PRIVATBK  O.N.',
'QB7.MU': 'QUIRIN PRIVATBK  O.N.',
'QB7.BE': 'QUIRIN PRIVATBK  O.N.',
'QB7.F': 'QUIRIN PRIVATBK  O.N.',
'QLD.MX': 'PROSHARES TRUST PSHS ULTRA QQQ',
'QD78.DE': 'I.X.S+P500 2XL.D.S.1C DL',
'QD7S.DE': 'I.XTRA.S+P500I.D.S.1C SK',
'QD7F.DE': 'I.X.S+P500 2X L.D.S.1C DL',
'QD7E.DE': 'I.X.S+P500 2X I.D.S.1C DL',
'QARUSD=X': 'QAR/USD',
'QARAED=X': 'QAR/AED',
'QAREUR=X': 'QAR/EUR',
'QAROMR=X': 'QAR/OMR',
'QARTHX=X': 'QAR/THX',
'QARJPY=X': 'QAR/JPY',
'QARXDR=X': 'QAR/XDR',
'QARBRX=X': 'QAR/BRX',
'QARSGD=X': 'QAR/SGD',
'QARPKR=X': 'QAR/PKR',
'QARGBP=X': 'QAR/GBP',
'QADA': 'QAD Inc.',
'QADB': 'QAD Inc.',
'Q01.SI': 'QAF',
'QASH-USD': 'QASH USD',
'QADB.BE': 'QAD INC. CL.B',
'QASH-ETH': 'QASH ETH',
'QASH-EUR': 'QASH EUR',
'QAN.MU': 'QANTAS AIRWAYS',
'QASH-RUB': 'QASH RUB',
'QFSOC.MI': 'QF SOCRATE',
'QGEN': 'Qiagen N.V.',
'QIW.F': 'QIWI B SP.ADRS 1/EO-',
'QIW.MU': 'QIWI B SP.ADRS 1/EO-',
'QIN.HM': 'QINGLING MOTORS CO. H YC1',
'QIW.DU': 'QIWI B SP.ADRS 1/EO-',
'QIW.BE': 'QIWI B SP.ADRS 1/EO-',
'QKLS': 'QKL STORES INC',
'QVM': 'Arrow QVM Equity Factor ETF',
'QRVO': 'Qorvo',
'QRF.BR': 'QRF',
'QTUM-USD': 'Qtum USD',
'QTUM-EUR': 'Qtum EUR',
'QTS-PB': 'QTS Realty Trust',
'QTS-PA': 'QTS Realty Trust',
'QTVLF': 'QT VASCULAR LTD',
'QTUM-RUB': 'Qtum RUB',
'QR3.F': 'QTS RLTY TR.CL.A  DL-',
'QLGN': 'Qualigen Therapeutics',
'QNTA': 'QUANTA INC',
'QLYS': 'Qualys',
'QTRRF': 'QUATERRA RESOURCES INC',
'QUIS.V': 'QUISITIVE TECHNOLOGY SOLUTIONS',
'QUOT': 'Quotient Technology Inc.',
'QTRH.TO': 'QUARTERHILL INC',
'QNST': 'QuinStreet',
'QST.V': 'Questor Technology Inc.',
'QUISF': 'QUISITIVE TECHNOLOGY SOLUTIONS',
'QMCI': 'QUOTEMEDIA INC',
'QNT-USD': 'Quant USD',
'QTRHF': 'QUARTERHILL INC',
'QTA.V': 'Quaterra Resources Inc.',
'QDROF': 'QUADRO RESOURCES LTD',
'QENC': 'QUEENCH INC',
'QRO.V': 'QUADRO RESOURCES INC',
'QCI.DE': 'QUALCOMM INC.  DL-',
'QCA.CN': 'QuinsamCap',
'QDT.PA': 'QUADIENT',
'QBAT.CN': 'QuantumBatMetal',
'QCOM.MX': 'QUALCOMM INC',
'QRSVX': 'Queens Road Small Cap Value Fun',
'QRL-USD': 'QuantumResistantLedger USD',
'QLRD.TA': 'QUICKLIZARD LTD',
'QGSI': 'QUANTGATE SYS INC',
'QCOM.VI': 'QUALCOMM INC',
'QLTU.TA': 'QUALITAU',
'QUINENCO.SN': 'QUINENCO SA',
'QCOM.BA': 'QUALCOMM INC',
'QCOM.SN': 'QUALCOMM INC',
'QRK-USD': 'Quark USD',
'QBCRF': 'QUEBECOR INC',
'QUINTEGRA.BO': 'QUINTEGRA SOLUTIONS LTD.',
'QCOMC.BA': 'QUALCOMM INC',
'QCI.F': 'QUALCOMM INC.  DL-',
'QFEEF': 'QUICKFEE LTD',
'QUTAA.PA': 'QUARTUS7%19JUN22',
'QRK-RUB': 'Quark RUB',
'QNT-EUR': 'Quant EUR',
'QR2.SG': 'Quaterra Resources Inc. Registe',
'QKL1.DU': 'QUICKLOGIC CORP.  DL-',
'QNCO.TA': 'QUEENCO LTD(Y.Z)',
'QAA.SG': 'QUANTA SERVICES INC. Registered',
'QCI.DU': 'QUALCOMM INC.  DL-',
'QCI.HA': 'QUALCOMM INC.  DL-',
'QCOMD.BA': 'QUALCOMM INC',
'QB3.F': 'QUEBECOR INC. B SUB.VTG',
'QRK-EUR': 'Quark EUR',
'QCI.BE': 'QUALCOMM INC.  DL-',
'QCI.MU': 'QUALCOMM INC.  DL-',
'QRL-EUR': 'QuantumResistantLedger EUR',
'QL1.BE': 'QUIDEL CORP.  DL-',
'QA7.F': 'QUBICGAMES S.A.  ZY -',
'QR2.MU': 'QUATERRA RES INC.',
'QAA.MU': 'QUANTA SVCS  DL-',
'QUIS-WT.V': 'QUISITIVE TECHNOLOGY SOLUTIONS',
'QAA.F': 'QUANTA SVCS  DL-',
'QR2.F': 'QUATERRA RES INC.',
'QRL-RUB': 'QuantumResistantLedger RUB',
'QKL1.MU': 'QUICKLOGIC CORP.  DL-',
'QA7.MU': 'QUBICGAMES S.A.  ZY -',
'QAA.DU': 'QUANTA SVCS  DL-',
'QUINTEGRA.NS': 'QUINTEGRA SOLUTION',
'QL1.DU': 'QUIDEL CORP.  DL-',
'QL1.MU': 'QUIDEL CORP.  DL-',
'QCI.SG': 'QUALCOMM INC. Registered Shares',
'QKL1.BE': 'QUICKLOGIC CORP.  DL-',
'QCI.HM': 'QUALCOMM INC.  DL-',
'QTZ.CN': 'QueSilicaRes',
'QL1.F': 'QUIDEL CORP.  DL-',
'QNT-RUB': 'Quant RUB',
'QVCC': 'QVC',
'QVCD': 'QVC',
'QUAL.AT': 'QUALITY & RELIABILITY S.A.',
'QLMICX': '1919 Variable Socially Responsi',
'QFB1.F': 'ULTRA RES INC.',
'QFB1.BE': 'ULTRA RES INC.',
'Q2R.Z': 'STXE TM RETAIL RE.EUR',
'Q2Q.Z': 'STXE TM RETAIL PR.USD',
'Q8H.Z': 'STX.EU.400 RET.NR USD',
'Q1S.Z': 'STXE 600 RETAIL RE.EUR',
'Q1Q.Z': 'STXE 600 RETAIL PR.EUR',
'Q2S.Z': 'STXE TM RETAIL RE.USD',
'Q2P.Z': 'STXE TM RETAIL PR.EUR',
'Q8F.Z': 'STX.EU.400 RET.PR USD',
'Q8J.Z': 'STX.EU.400 RET.NR EUR',
'Q1T.Z': 'STXE 600 RETAIL RE.USD',
'Q8G.Z': 'STX.EU.400 RET.PR EUR',
'Q1R.Z': 'STXE 600 RETAIL PR.USD',
'QSU.F': 'SCSK CORP.',
'QD7Y.DE': 'I.XTRA.MSCI TAI.1C SEK',
'QD7J.DE': 'I.XTRA.MSCI WO.SW.1C SEK',
'QD7U.DE': 'I.XTRA.MSCI EM SW.1C SEK',
'QD7M.DE': 'I.XTRA.MSCI USA S.1C SEK',
'Q7L.Z': 'ESTX TM SFTW.SERVS RE.USD',
'QFP.SG': 'Element 25 Ltd. Registered Shar',
'QMC.SG': 'SMC CORP. Registered Shares o.N',
'QSHI': 'None',
'QSII': 'None',
'QSIM': 'None',
'QD7V.DE': 'I.XTRA.MSCI EM A.S.1C SK',
'QD7R.DE': 'I.XTRA.ESTX50 S.D.S.1C SK',
'QD7P.DE': 'I.XTRA.S.E.600 B.S.1C SK',
'QD7Q.DE': 'I.XTRA.SH.DAX D.S.1C SK',
'QNS.SI': '$ SouthernAlliance',
'QOL.F': 'SOL S.P.A.  EO 0',
'Q1M.Z': 'STXE 600 P.H.GD. PR.USD',
'Q79.Z': 'STX.EU.400T.+L.NR USD',
'Q5P.Z': 'STXE TM SW.+CO.SER.RE EUR',
'Q1L.Z': 'STXE 600 P.H.GD. PR.EUR',
'Q5T.Z': 'STXE TECH.HARD.EQ.RE EUR',
'Q5U.Z': 'STXE TECH.HARD.EQ.RE USD',
'Q5M.Z': 'STXE TM SW.+CO.SER.PR EUR',
'Q8A.Z': 'STX.EU.400T.+L.NR EUR',
'Q1P.Z': 'STXE 600 P.H.GD. RE.USD',
'Q8D.Z': 'STX.EU.400P.+H.G.IN.NR DL',
'Q8B.Z': 'STX.EU.400P.+H.G.IN.PR DL',
'Q5N.Z': 'STXE TM SW.+CO.SER.PR USD',
'Q5S.Z': 'STXE TECH.HARD.EQ.PR USD',
'Q5Q.Z': 'STXE TM SW.+CO.SER.RE USD',
'Q78.Z': 'STX.EU.400T.+L.PR EUR',
'Q77.Z': 'STX.EU.400T.+L.PR USD',
'Q5R.Z': 'STXE TECH.HARD.EQ.PR EUR',
'QSOA.MU': 'SURFACE ONCOLOGY DL-',
'QTRH': 'None',
'QUSA': 'None',
'QAR=X': 'USD/QAR',
'QU5A.MU': 'PADAENG IND. -NVDR- BA 10',
